<?xml version="1.0" encoding="utf-8"?><Database Name="DH_CODONG" Class="TanHoaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HP_G7\KD;Initial Catalog=DH_CODONG;Persist Security Info=True;User ID=sa" SettingsObjectName="KETQUa.Properties.Settings" SettingsPropertyName="DH_CODONGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DSCODONG_THAMDU" Member="DSCODONG_THAMDUs">
    <Type Name="DSCODONG_THAMDU">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STTCD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MACD" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NGAYCAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NOICAP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CDGD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PHONGTOA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYVAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>