<?xml version="1.0" encoding="utf-8"?><Database Name="CallCenter" Class="CallCenterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HP_G7\KD;Initial Catalog=CallCenter;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CallCenterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KT_DongNuoc" Member="KT_DongNuocs">
    <Type Name="KT_DongNuoc">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DongMo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="lat" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="lng" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TuNgay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DenNgay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TuGio" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DenGio" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KT_BaoBe" Member="KT_BaoBes">
    <Type Name="KT_BaoBe">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lat" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Lng" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoaiBao" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phuong" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayBao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTiepNhan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThucHien" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoaiThucHien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KetQua" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Img" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FilePdf" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>