<?xml version="1.0" encoding="utf-8"?><Database Name="DocSoTH" Class="DocSoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=113.161.88.180,1833\KD;Initial Catalog=DocSoTH;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DocSoTHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DocSo" Member="DocSos">
    <Type Name="DocSo">
      <Column Name="DocSoID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MLT1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MLT2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SoNhaCu" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SoNhaMoi" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Duong" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ky" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dot" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="May" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TBTT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TamTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CSCu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CSMoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodeCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodeMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TTDHNCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TTDHNMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TieuThuCu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuThuMoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TuNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DenNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TienNuoc" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BVMT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoThanCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SoThanMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HieuCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HieuMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CoCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CoMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GiengCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GiengMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Van1Cu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Van1Moi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MVCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MVMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChiCoCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChiCoMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChiThanCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChiThanMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ViTriCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ViTriMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CapDoCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CapDoMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CongDungCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CongDungMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DMACu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DMAMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GhiChuKH" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GhiChuDS" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GhiChuTV" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NVGHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOGHI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BARCODE" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="SOLANGHI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GPSDATA" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="StaCapNhat" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NVCapNhat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TODS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>