#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachHang.DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KYTHUAT")]
	public partial class KyThuatDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKT_DongNuoc(KT_DongNuoc instance);
    partial void UpdateKT_DongNuoc(KT_DongNuoc instance);
    partial void DeleteKT_DongNuoc(KT_DongNuoc instance);
    partial void InsertKT_BaoBe(KT_BaoBe instance);
    partial void UpdateKT_BaoBe(KT_BaoBe instance);
    partial void DeleteKT_BaoBe(KT_BaoBe instance);
    partial void InsertKT_Van(KT_Van instance);
    partial void UpdateKT_Van(KT_Van instance);
    partial void DeleteKT_Van(KT_Van instance);
    #endregion
		
		public KyThuatDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["KYTHUATConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KyThuatDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KyThuatDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KyThuatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KyThuatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KT_DongNuoc> KT_DongNuocs
		{
			get
			{
				return this.GetTable<KT_DongNuoc>();
			}
		}
		
		public System.Data.Linq.Table<KT_BaoBe> KT_BaoBes
		{
			get
			{
				return this.GetTable<KT_BaoBe>();
			}
		}
		
		public System.Data.Linq.Table<KT_Van> KT_Vans
		{
			get
			{
				return this.GetTable<KT_Van>();
			}
		}
		
		public System.Data.Linq.Table<DongHo> DongHos
		{
			get
			{
				return this.GetTable<DongHo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KT_DongNuoc")]
	public partial class KT_DongNuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<bool> _Loai;
		
		private System.Nullable<bool> _DongMo;
		
		private string _lat;
		
		private string _lng;
		
		private string _DiaChi;
		
		private System.Nullable<System.DateTime> _TuNgay;
		
		private System.Nullable<System.DateTime> _DenNgay;
		
		private string _TuGio;
		
		private string _DenGio;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLoaiChanging(System.Nullable<bool> value);
    partial void OnLoaiChanged();
    partial void OnDongMoChanging(System.Nullable<bool> value);
    partial void OnDongMoChanged();
    partial void OnlatChanging(string value);
    partial void OnlatChanged();
    partial void OnlngChanging(string value);
    partial void OnlngChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnTuNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnTuNgayChanged();
    partial void OnDenNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnDenNgayChanged();
    partial void OnTuGioChanging(string value);
    partial void OnTuGioChanged();
    partial void OnDenGioChanging(string value);
    partial void OnDenGioChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(string value);
    partial void OnModifyByChanged();
    #endregion
		
		public KT_DongNuoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="Bit")]
		public System.Nullable<bool> Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DongMo", DbType="Bit")]
		public System.Nullable<bool> DongMo
		{
			get
			{
				return this._DongMo;
			}
			set
			{
				if ((this._DongMo != value))
				{
					this.OnDongMoChanging(value);
					this.SendPropertyChanging();
					this._DongMo = value;
					this.SendPropertyChanged("DongMo");
					this.OnDongMoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="NVarChar(20)")]
		public string lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lng", DbType="VarChar(20)")]
		public string lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				if ((this._lng != value))
				{
					this.OnlngChanging(value);
					this.SendPropertyChanging();
					this._lng = value;
					this.SendPropertyChanged("lng");
					this.OnlngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuNgay", DbType="DateTime")]
		public System.Nullable<System.DateTime> TuNgay
		{
			get
			{
				return this._TuNgay;
			}
			set
			{
				if ((this._TuNgay != value))
				{
					this.OnTuNgayChanging(value);
					this.SendPropertyChanging();
					this._TuNgay = value;
					this.SendPropertyChanged("TuNgay");
					this.OnTuNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenNgay", DbType="DateTime")]
		public System.Nullable<System.DateTime> DenNgay
		{
			get
			{
				return this._DenNgay;
			}
			set
			{
				if ((this._DenNgay != value))
				{
					this.OnDenNgayChanging(value);
					this.SendPropertyChanging();
					this._DenNgay = value;
					this.SendPropertyChanged("DenNgay");
					this.OnDenNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuGio", DbType="NVarChar(20)")]
		public string TuGio
		{
			get
			{
				return this._TuGio;
			}
			set
			{
				if ((this._TuGio != value))
				{
					this.OnTuGioChanging(value);
					this.SendPropertyChanging();
					this._TuGio = value;
					this.SendPropertyChanged("TuGio");
					this.OnTuGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenGio", DbType="NVarChar(20)")]
		public string DenGio
		{
			get
			{
				return this._DenGio;
			}
			set
			{
				if ((this._DenGio != value))
				{
					this.OnDenGioChanging(value);
					this.SendPropertyChanging();
					this._DenGio = value;
					this.SendPropertyChanged("DenGio");
					this.OnDenGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="VarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="VarChar(50)")]
		public string ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KT_BaoBe")]
	public partial class KT_BaoBe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _TinhTrang;
		
		private string _Lat;
		
		private string _Lng;
		
		private string _SoDT;
		
		private string _LoaiBao;
		
		private string _SoNha;
		
		private string _TenDuong;
		
		private string _Phuong;
		
		private string _Quan;
		
		private System.Nullable<System.DateTime> _NgayBao;
		
		private string _GhiChu;
		
		private string _DonViSuaBe;
		
		private System.Nullable<System.DateTime> _NgayChuyenSuaBe;
		
		private System.Nullable<System.DateTime> _NgayTiepNhan;
		
		private System.Nullable<System.DateTime> _NgayThucHien;
		
		private System.Nullable<int> _LoaiThucHien;
		
		private System.Nullable<System.DateTime> _TuGio;
		
		private System.Nullable<System.DateTime> _DenGio;
		
		private string _KetQua;
		
		private string _NVGiamSat;
		
		private string _NVSuaBe;
		
		private string _Img;
		
		private string _FilePdf;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyBy;
		
		private string _SoHoSo;
		
		private string _MaDMA;
		
		private string _SoBangKe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    partial void OnLatChanging(string value);
    partial void OnLatChanged();
    partial void OnLngChanging(string value);
    partial void OnLngChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnLoaiBaoChanging(string value);
    partial void OnLoaiBaoChanged();
    partial void OnSoNhaChanging(string value);
    partial void OnSoNhaChanged();
    partial void OnTenDuongChanging(string value);
    partial void OnTenDuongChanged();
    partial void OnPhuongChanging(string value);
    partial void OnPhuongChanged();
    partial void OnQuanChanging(string value);
    partial void OnQuanChanged();
    partial void OnNgayBaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBaoChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnDonViSuaBeChanging(string value);
    partial void OnDonViSuaBeChanged();
    partial void OnNgayChuyenSuaBeChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenSuaBeChanged();
    partial void OnNgayTiepNhanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTiepNhanChanged();
    partial void OnNgayThucHienChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThucHienChanged();
    partial void OnLoaiThucHienChanging(System.Nullable<int> value);
    partial void OnLoaiThucHienChanged();
    partial void OnTuGioChanging(System.Nullable<System.DateTime> value);
    partial void OnTuGioChanged();
    partial void OnDenGioChanging(System.Nullable<System.DateTime> value);
    partial void OnDenGioChanged();
    partial void OnKetQuaChanging(string value);
    partial void OnKetQuaChanged();
    partial void OnNVGiamSatChanging(string value);
    partial void OnNVGiamSatChanged();
    partial void OnNVSuaBeChanging(string value);
    partial void OnNVSuaBeChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    partial void OnFilePdfChanging(string value);
    partial void OnFilePdfChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(string value);
    partial void OnModifyByChanged();
    partial void OnSoHoSoChanging(string value);
    partial void OnSoHoSoChanged();
    partial void OnMaDMAChanging(string value);
    partial void OnMaDMAChanged();
    partial void OnSoBangKeChanging(string value);
    partial void OnSoBangKeChanged();
    #endregion
		
		public KT_BaoBe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="NVarChar(20)")]
		public string Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lng", DbType="VarChar(20)")]
		public string Lng
		{
			get
			{
				return this._Lng;
			}
			set
			{
				if ((this._Lng != value))
				{
					this.OnLngChanging(value);
					this.SendPropertyChanging();
					this._Lng = value;
					this.SendPropertyChanged("Lng");
					this.OnLngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="VarChar(50)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBao", DbType="NVarChar(50)")]
		public string LoaiBao
		{
			get
			{
				return this._LoaiBao;
			}
			set
			{
				if ((this._LoaiBao != value))
				{
					this.OnLoaiBaoChanging(value);
					this.SendPropertyChanging();
					this._LoaiBao = value;
					this.SendPropertyChanged("LoaiBao");
					this.OnLoaiBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNha", DbType="NVarChar(MAX)")]
		public string SoNha
		{
			get
			{
				return this._SoNha;
			}
			set
			{
				if ((this._SoNha != value))
				{
					this.OnSoNhaChanging(value);
					this.SendPropertyChanging();
					this._SoNha = value;
					this.SendPropertyChanged("SoNha");
					this.OnSoNhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuong", DbType="NVarChar(MAX)")]
		public string TenDuong
		{
			get
			{
				return this._TenDuong;
			}
			set
			{
				if ((this._TenDuong != value))
				{
					this.OnTenDuongChanging(value);
					this.SendPropertyChanging();
					this._TenDuong = value;
					this.SendPropertyChanged("TenDuong");
					this.OnTenDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phuong", DbType="VarChar(50)")]
		public string Phuong
		{
			get
			{
				return this._Phuong;
			}
			set
			{
				if ((this._Phuong != value))
				{
					this.OnPhuongChanging(value);
					this.SendPropertyChanging();
					this._Phuong = value;
					this.SendPropertyChanged("Phuong");
					this.OnPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quan", DbType="VarChar(50)")]
		public string Quan
		{
			get
			{
				return this._Quan;
			}
			set
			{
				if ((this._Quan != value))
				{
					this.OnQuanChanging(value);
					this.SendPropertyChanging();
					this._Quan = value;
					this.SendPropertyChanged("Quan");
					this.OnQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBao
		{
			get
			{
				return this._NgayBao;
			}
			set
			{
				if ((this._NgayBao != value))
				{
					this.OnNgayBaoChanging(value);
					this.SendPropertyChanging();
					this._NgayBao = value;
					this.SendPropertyChanged("NgayBao");
					this.OnNgayBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViSuaBe", DbType="NVarChar(50)")]
		public string DonViSuaBe
		{
			get
			{
				return this._DonViSuaBe;
			}
			set
			{
				if ((this._DonViSuaBe != value))
				{
					this.OnDonViSuaBeChanging(value);
					this.SendPropertyChanging();
					this._DonViSuaBe = value;
					this.SendPropertyChanged("DonViSuaBe");
					this.OnDonViSuaBeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyenSuaBe", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChuyenSuaBe
		{
			get
			{
				return this._NgayChuyenSuaBe;
			}
			set
			{
				if ((this._NgayChuyenSuaBe != value))
				{
					this.OnNgayChuyenSuaBeChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyenSuaBe = value;
					this.SendPropertyChanged("NgayChuyenSuaBe");
					this.OnNgayChuyenSuaBeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTiepNhan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTiepNhan
		{
			get
			{
				return this._NgayTiepNhan;
			}
			set
			{
				if ((this._NgayTiepNhan != value))
				{
					this.OnNgayTiepNhanChanging(value);
					this.SendPropertyChanging();
					this._NgayTiepNhan = value;
					this.SendPropertyChanged("NgayTiepNhan");
					this.OnNgayTiepNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThucHien", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThucHien
		{
			get
			{
				return this._NgayThucHien;
			}
			set
			{
				if ((this._NgayThucHien != value))
				{
					this.OnNgayThucHienChanging(value);
					this.SendPropertyChanging();
					this._NgayThucHien = value;
					this.SendPropertyChanged("NgayThucHien");
					this.OnNgayThucHienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiThucHien", DbType="Int")]
		public System.Nullable<int> LoaiThucHien
		{
			get
			{
				return this._LoaiThucHien;
			}
			set
			{
				if ((this._LoaiThucHien != value))
				{
					this.OnLoaiThucHienChanging(value);
					this.SendPropertyChanging();
					this._LoaiThucHien = value;
					this.SendPropertyChanged("LoaiThucHien");
					this.OnLoaiThucHienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuGio", DbType="DateTime")]
		public System.Nullable<System.DateTime> TuGio
		{
			get
			{
				return this._TuGio;
			}
			set
			{
				if ((this._TuGio != value))
				{
					this.OnTuGioChanging(value);
					this.SendPropertyChanging();
					this._TuGio = value;
					this.SendPropertyChanged("TuGio");
					this.OnTuGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenGio", DbType="DateTime")]
		public System.Nullable<System.DateTime> DenGio
		{
			get
			{
				return this._DenGio;
			}
			set
			{
				if ((this._DenGio != value))
				{
					this.OnDenGioChanging(value);
					this.SendPropertyChanging();
					this._DenGio = value;
					this.SendPropertyChanged("DenGio");
					this.OnDenGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetQua", DbType="NVarChar(MAX)")]
		public string KetQua
		{
			get
			{
				return this._KetQua;
			}
			set
			{
				if ((this._KetQua != value))
				{
					this.OnKetQuaChanging(value);
					this.SendPropertyChanging();
					this._KetQua = value;
					this.SendPropertyChanged("KetQua");
					this.OnKetQuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NVGiamSat", DbType="NVarChar(500)")]
		public string NVGiamSat
		{
			get
			{
				return this._NVGiamSat;
			}
			set
			{
				if ((this._NVGiamSat != value))
				{
					this.OnNVGiamSatChanging(value);
					this.SendPropertyChanging();
					this._NVGiamSat = value;
					this.SendPropertyChanged("NVGiamSat");
					this.OnNVGiamSatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NVSuaBe", DbType="NVarChar(500)")]
		public string NVSuaBe
		{
			get
			{
				return this._NVSuaBe;
			}
			set
			{
				if ((this._NVSuaBe != value))
				{
					this.OnNVSuaBeChanging(value);
					this.SendPropertyChanging();
					this._NVSuaBe = value;
					this.SendPropertyChanged("NVSuaBe");
					this.OnNVSuaBeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="NVarChar(500)")]
		public string Img
		{
			get
			{
				return this._Img;
			}
			set
			{
				if ((this._Img != value))
				{
					this.OnImgChanging(value);
					this.SendPropertyChanging();
					this._Img = value;
					this.SendPropertyChanged("Img");
					this.OnImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilePdf", DbType="NVarChar(500)")]
		public string FilePdf
		{
			get
			{
				return this._FilePdf;
			}
			set
			{
				if ((this._FilePdf != value))
				{
					this.OnFilePdfChanging(value);
					this.SendPropertyChanging();
					this._FilePdf = value;
					this.SendPropertyChanged("FilePdf");
					this.OnFilePdfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="VarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="VarChar(50)")]
		public string ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHoSo", DbType="NVarChar(50)")]
		public string SoHoSo
		{
			get
			{
				return this._SoHoSo;
			}
			set
			{
				if ((this._SoHoSo != value))
				{
					this.OnSoHoSoChanging(value);
					this.SendPropertyChanging();
					this._SoHoSo = value;
					this.SendPropertyChanged("SoHoSo");
					this.OnSoHoSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDMA", DbType="NVarChar(50)")]
		public string MaDMA
		{
			get
			{
				return this._MaDMA;
			}
			set
			{
				if ((this._MaDMA != value))
				{
					this.OnMaDMAChanging(value);
					this.SendPropertyChanging();
					this._MaDMA = value;
					this.SendPropertyChanged("MaDMA");
					this.OnMaDMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBangKe", DbType="VarChar(50)")]
		public string SoBangKe
		{
			get
			{
				return this._SoBangKe;
			}
			set
			{
				if ((this._SoBangKe != value))
				{
					this.OnSoBangKeChanging(value);
					this.SendPropertyChanging();
					this._SoBangKe = value;
					this.SendPropertyChanged("SoBangKe");
					this.OnSoBangKeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KT_Van")]
	public partial class KT_Van : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _STT;
		
		private string _Lat;
		
		private string _Lng;
		
		private string _TuyenOng;
		
		private string _CoVan;
		
		private string _MaSo;
		
		private string _TenDuong;
		
		private string _DiaChi;
		
		private string _Phuong;
		
		private string _Quan;
		
		private System.Nullable<bool> _ChanTuyen;
		
		private System.Nullable<bool> _XaCan;
		
		private System.Nullable<bool> _TCH;
		
		private System.Nullable<bool> _TLKCoLon;
		
		private System.Nullable<bool> _VanBien;
		
		private System.Nullable<bool> _LoaiVan;
		
		private string _ChieuDong;
		
		private string _SoVong;
		
		private string _DoSau;
		
		private string _ThongTinMang;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _Xoa;
		
		private System.Nullable<int> _NgayXaCan;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSTTChanging(string value);
    partial void OnSTTChanged();
    partial void OnLatChanging(string value);
    partial void OnLatChanged();
    partial void OnLngChanging(string value);
    partial void OnLngChanged();
    partial void OnTuyenOngChanging(string value);
    partial void OnTuyenOngChanged();
    partial void OnCoVanChanging(string value);
    partial void OnCoVanChanged();
    partial void OnMaSoChanging(string value);
    partial void OnMaSoChanged();
    partial void OnTenDuongChanging(string value);
    partial void OnTenDuongChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnPhuongChanging(string value);
    partial void OnPhuongChanged();
    partial void OnQuanChanging(string value);
    partial void OnQuanChanged();
    partial void OnChanTuyenChanging(System.Nullable<bool> value);
    partial void OnChanTuyenChanged();
    partial void OnXaCanChanging(System.Nullable<bool> value);
    partial void OnXaCanChanged();
    partial void OnTCHChanging(System.Nullable<bool> value);
    partial void OnTCHChanged();
    partial void OnTLKCoLonChanging(System.Nullable<bool> value);
    partial void OnTLKCoLonChanged();
    partial void OnVanBienChanging(System.Nullable<bool> value);
    partial void OnVanBienChanged();
    partial void OnLoaiVanChanging(System.Nullable<bool> value);
    partial void OnLoaiVanChanged();
    partial void OnChieuDongChanging(string value);
    partial void OnChieuDongChanged();
    partial void OnSoVongChanging(string value);
    partial void OnSoVongChanged();
    partial void OnDoSauChanging(string value);
    partial void OnDoSauChanged();
    partial void OnThongTinMangChanging(string value);
    partial void OnThongTinMangChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnXoaChanging(System.Nullable<bool> value);
    partial void OnXoaChanged();
    partial void OnNgayXaCanChanging(System.Nullable<int> value);
    partial void OnNgayXaCanChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(string value);
    partial void OnModifyByChanged();
    #endregion
		
		public KT_Van()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="VarChar(50)")]
		public string STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="NVarChar(50)")]
		public string Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lng", DbType="NVarChar(50)")]
		public string Lng
		{
			get
			{
				return this._Lng;
			}
			set
			{
				if ((this._Lng != value))
				{
					this.OnLngChanging(value);
					this.SendPropertyChanging();
					this._Lng = value;
					this.SendPropertyChanged("Lng");
					this.OnLngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuyenOng", DbType="NVarChar(50)")]
		public string TuyenOng
		{
			get
			{
				return this._TuyenOng;
			}
			set
			{
				if ((this._TuyenOng != value))
				{
					this.OnTuyenOngChanging(value);
					this.SendPropertyChanging();
					this._TuyenOng = value;
					this.SendPropertyChanged("TuyenOng");
					this.OnTuyenOngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoVan", DbType="VarChar(50)")]
		public string CoVan
		{
			get
			{
				return this._CoVan;
			}
			set
			{
				if ((this._CoVan != value))
				{
					this.OnCoVanChanging(value);
					this.SendPropertyChanging();
					this._CoVan = value;
					this.SendPropertyChanged("CoVan");
					this.OnCoVanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSo", DbType="NVarChar(50)")]
		public string MaSo
		{
			get
			{
				return this._MaSo;
			}
			set
			{
				if ((this._MaSo != value))
				{
					this.OnMaSoChanging(value);
					this.SendPropertyChanging();
					this._MaSo = value;
					this.SendPropertyChanged("MaSo");
					this.OnMaSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuong", DbType="NVarChar(50)")]
		public string TenDuong
		{
			get
			{
				return this._TenDuong;
			}
			set
			{
				if ((this._TenDuong != value))
				{
					this.OnTenDuongChanging(value);
					this.SendPropertyChanging();
					this._TenDuong = value;
					this.SendPropertyChanged("TenDuong");
					this.OnTenDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phuong", DbType="VarChar(50)")]
		public string Phuong
		{
			get
			{
				return this._Phuong;
			}
			set
			{
				if ((this._Phuong != value))
				{
					this.OnPhuongChanging(value);
					this.SendPropertyChanging();
					this._Phuong = value;
					this.SendPropertyChanged("Phuong");
					this.OnPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quan", DbType="VarChar(50)")]
		public string Quan
		{
			get
			{
				return this._Quan;
			}
			set
			{
				if ((this._Quan != value))
				{
					this.OnQuanChanging(value);
					this.SendPropertyChanging();
					this._Quan = value;
					this.SendPropertyChanged("Quan");
					this.OnQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChanTuyen", DbType="Bit")]
		public System.Nullable<bool> ChanTuyen
		{
			get
			{
				return this._ChanTuyen;
			}
			set
			{
				if ((this._ChanTuyen != value))
				{
					this.OnChanTuyenChanging(value);
					this.SendPropertyChanging();
					this._ChanTuyen = value;
					this.SendPropertyChanged("ChanTuyen");
					this.OnChanTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XaCan", DbType="Bit")]
		public System.Nullable<bool> XaCan
		{
			get
			{
				return this._XaCan;
			}
			set
			{
				if ((this._XaCan != value))
				{
					this.OnXaCanChanging(value);
					this.SendPropertyChanging();
					this._XaCan = value;
					this.SendPropertyChanged("XaCan");
					this.OnXaCanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCH", DbType="Bit")]
		public System.Nullable<bool> TCH
		{
			get
			{
				return this._TCH;
			}
			set
			{
				if ((this._TCH != value))
				{
					this.OnTCHChanging(value);
					this.SendPropertyChanging();
					this._TCH = value;
					this.SendPropertyChanged("TCH");
					this.OnTCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLKCoLon", DbType="Bit")]
		public System.Nullable<bool> TLKCoLon
		{
			get
			{
				return this._TLKCoLon;
			}
			set
			{
				if ((this._TLKCoLon != value))
				{
					this.OnTLKCoLonChanging(value);
					this.SendPropertyChanging();
					this._TLKCoLon = value;
					this.SendPropertyChanged("TLKCoLon");
					this.OnTLKCoLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VanBien", DbType="Bit")]
		public System.Nullable<bool> VanBien
		{
			get
			{
				return this._VanBien;
			}
			set
			{
				if ((this._VanBien != value))
				{
					this.OnVanBienChanging(value);
					this.SendPropertyChanging();
					this._VanBien = value;
					this.SendPropertyChanged("VanBien");
					this.OnVanBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiVan", DbType="Bit")]
		public System.Nullable<bool> LoaiVan
		{
			get
			{
				return this._LoaiVan;
			}
			set
			{
				if ((this._LoaiVan != value))
				{
					this.OnLoaiVanChanging(value);
					this.SendPropertyChanging();
					this._LoaiVan = value;
					this.SendPropertyChanged("LoaiVan");
					this.OnLoaiVanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChieuDong", DbType="NVarChar(50)")]
		public string ChieuDong
		{
			get
			{
				return this._ChieuDong;
			}
			set
			{
				if ((this._ChieuDong != value))
				{
					this.OnChieuDongChanging(value);
					this.SendPropertyChanging();
					this._ChieuDong = value;
					this.SendPropertyChanged("ChieuDong");
					this.OnChieuDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoVong", DbType="NVarChar(50)")]
		public string SoVong
		{
			get
			{
				return this._SoVong;
			}
			set
			{
				if ((this._SoVong != value))
				{
					this.OnSoVongChanging(value);
					this.SendPropertyChanging();
					this._SoVong = value;
					this.SendPropertyChanged("SoVong");
					this.OnSoVongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoSau", DbType="NVarChar(50)")]
		public string DoSau
		{
			get
			{
				return this._DoSau;
			}
			set
			{
				if ((this._DoSau != value))
				{
					this.OnDoSauChanging(value);
					this.SendPropertyChanging();
					this._DoSau = value;
					this.SendPropertyChanged("DoSau");
					this.OnDoSauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinMang", DbType="NVarChar(50)")]
		public string ThongTinMang
		{
			get
			{
				return this._ThongTinMang;
			}
			set
			{
				if ((this._ThongTinMang != value))
				{
					this.OnThongTinMangChanging(value);
					this.SendPropertyChanging();
					this._ThongTinMang = value;
					this.SendPropertyChanged("ThongTinMang");
					this.OnThongTinMangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xoa", DbType="Bit")]
		public System.Nullable<bool> Xoa
		{
			get
			{
				return this._Xoa;
			}
			set
			{
				if ((this._Xoa != value))
				{
					this.OnXoaChanging(value);
					this.SendPropertyChanging();
					this._Xoa = value;
					this.SendPropertyChanged("Xoa");
					this.OnXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXaCan", DbType="Int")]
		public System.Nullable<int> NgayXaCan
		{
			get
			{
				return this._NgayXaCan;
			}
			set
			{
				if ((this._NgayXaCan != value))
				{
					this.OnNgayXaCanChanging(value);
					this.SendPropertyChanging();
					this._NgayXaCan = value;
					this.SendPropertyChanged("NgayXaCan");
					this.OnNgayXaCanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="NVarChar(50)")]
		public string ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DongHo")]
	public partial class DongHo
	{
		
		private string _DBDONGHONUOC;
		
		private string _URL;
		
		private System.Nullable<double> _Lat;
		
		private System.Nullable<double> _Long;
		
		private System.Nullable<int> _DMA;
		
		public DongHo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBDONGHONUOC", DbType="NVarChar(255)")]
		public string DBDONGHONUOC
		{
			get
			{
				return this._DBDONGHONUOC;
			}
			set
			{
				if ((this._DBDONGHONUOC != value))
				{
					this._DBDONGHONUOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(255)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Float")]
		public System.Nullable<double> Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this._Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Long", DbType="Float")]
		public System.Nullable<double> Long
		{
			get
			{
				return this._Long;
			}
			set
			{
				if ((this._Long != value))
				{
					this._Long = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMA", DbType="Int")]
		public System.Nullable<int> DMA
		{
			get
			{
				return this._DMA;
			}
			set
			{
				if ((this._DMA != value))
				{
					this._DMA = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
