#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachHang.DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CAPNUOCTANHOA")]
	public partial class TanHoaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGNKDT_THONGTINDMA(GNKDT_THONGTINDMA instance);
    partial void UpdateGNKDT_THONGTINDMA(GNKDT_THONGTINDMA instance);
    partial void DeleteGNKDT_THONGTINDMA(GNKDT_THONGTINDMA instance);
    partial void InsertSYS_USER(SYS_USER instance);
    partial void UpdateSYS_USER(SYS_USER instance);
    partial void DeleteSYS_USER(SYS_USER instance);
    partial void InsertTB_DULIEUKHACHHANG(TB_DULIEUKHACHHANG instance);
    partial void UpdateTB_DULIEUKHACHHANG(TB_DULIEUKHACHHANG instance);
    partial void DeleteTB_DULIEUKHACHHANG(TB_DULIEUKHACHHANG instance);
    partial void InsertTB_DULIEUKHACHHANG_HUYDB(TB_DULIEUKHACHHANG_HUYDB instance);
    partial void UpdateTB_DULIEUKHACHHANG_HUYDB(TB_DULIEUKHACHHANG_HUYDB instance);
    partial void DeleteTB_DULIEUKHACHHANG_HUYDB(TB_DULIEUKHACHHANG_HUYDB instance);
    partial void InsertTB_DULIEUKHACHHANG_IMG(TB_DULIEUKHACHHANG_IMG instance);
    partial void UpdateTB_DULIEUKHACHHANG_IMG(TB_DULIEUKHACHHANG_IMG instance);
    partial void DeleteTB_DULIEUKHACHHANG_IMG(TB_DULIEUKHACHHANG_IMG instance);
    #endregion
		
		public TanHoaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CAPNUOCTANHOAConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TanHoaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TanHoaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TanHoaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TanHoaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GNKDT_THONGTINDMA> GNKDT_THONGTINDMAs
		{
			get
			{
				return this.GetTable<GNKDT_THONGTINDMA>();
			}
		}
		
		public System.Data.Linq.Table<SYS_USER> SYS_USERs
		{
			get
			{
				return this.GetTable<SYS_USER>();
			}
		}
		
		public System.Data.Linq.Table<TB_DULIEUKHACHHANG> TB_DULIEUKHACHHANGs
		{
			get
			{
				return this.GetTable<TB_DULIEUKHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<TB_DULIEUKHACHHANG_HUYDB> TB_DULIEUKHACHHANG_HUYDBs
		{
			get
			{
				return this.GetTable<TB_DULIEUKHACHHANG_HUYDB>();
			}
		}
		
		public System.Data.Linq.Table<TB_DULIEUKHACHHANG_IMG> TB_DULIEUKHACHHANG_IMGs
		{
			get
			{
				return this.GetTable<TB_DULIEUKHACHHANG_IMG>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BC_TONGKET")]
		public int BC_TONGKET([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TUNGAY", DbType="VarChar(50)")] string tUNGAY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DENNGAY", DbType="VarChar(50)")] string dENNGAY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HIEULUC", DbType="VarChar(50)")] string hIEULUC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tUNGAY, dENNGAY, hIEULUC);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THONGKEDHN_TP")]
		public int THONGKEDHN_TP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KY", DbType="Int")] System.Nullable<int> kY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kY, nAM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THONGKEDHN")]
		public int THONGKEDHN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KY", DbType="Int")] System.Nullable<int> kY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kY, nAM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THONGKEDHN_TB01")]
		public int THONGKEDHN_TB01([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KY", DbType="Int")] System.Nullable<int> kY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kY, nAM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THONGKEDHN_TB02")]
		public int THONGKEDHN_TB02([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KY", DbType="Int")] System.Nullable<int> kY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kY, nAM);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GNKDT_THONGTINDMA")]
	public partial class GNKDT_THONGTINDMA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MADMA;
		
		private System.Nullable<double> _TONGDHN;
		
		private System.Nullable<double> _KN_DHN;
		
		private System.Nullable<double> _KN_SANLUONG;
		
		private System.Nullable<double> _KT_DHN;
		
		private System.Nullable<double> _KT_SANLUONG;
		
		private System.Nullable<double> _TANGIAM_DHN;
		
		private System.Nullable<double> _TANGIAM_SANLUONG;
		
		private System.Nullable<double> _NT_DHN;
		
		private System.Nullable<double> _NT_SANLUONG;
		
		private System.Nullable<double> _NT_TANGIAM_DHN;
		
		private System.Nullable<double> _NT_TANGIAM_SANLUONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMADMAChanging(string value);
    partial void OnMADMAChanged();
    partial void OnTONGDHNChanging(System.Nullable<double> value);
    partial void OnTONGDHNChanged();
    partial void OnKN_DHNChanging(System.Nullable<double> value);
    partial void OnKN_DHNChanged();
    partial void OnKN_SANLUONGChanging(System.Nullable<double> value);
    partial void OnKN_SANLUONGChanged();
    partial void OnKT_DHNChanging(System.Nullable<double> value);
    partial void OnKT_DHNChanged();
    partial void OnKT_SANLUONGChanging(System.Nullable<double> value);
    partial void OnKT_SANLUONGChanged();
    partial void OnTANGIAM_DHNChanging(System.Nullable<double> value);
    partial void OnTANGIAM_DHNChanged();
    partial void OnTANGIAM_SANLUONGChanging(System.Nullable<double> value);
    partial void OnTANGIAM_SANLUONGChanged();
    partial void OnNT_DHNChanging(System.Nullable<double> value);
    partial void OnNT_DHNChanged();
    partial void OnNT_SANLUONGChanging(System.Nullable<double> value);
    partial void OnNT_SANLUONGChanged();
    partial void OnNT_TANGIAM_DHNChanging(System.Nullable<double> value);
    partial void OnNT_TANGIAM_DHNChanged();
    partial void OnNT_TANGIAM_SANLUONGChanging(System.Nullable<double> value);
    partial void OnNT_TANGIAM_SANLUONGChanged();
    #endregion
		
		public GNKDT_THONGTINDMA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADMA", DbType="NVarChar(250)")]
		public string MADMA
		{
			get
			{
				return this._MADMA;
			}
			set
			{
				if ((this._MADMA != value))
				{
					this.OnMADMAChanging(value);
					this.SendPropertyChanging();
					this._MADMA = value;
					this.SendPropertyChanged("MADMA");
					this.OnMADMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGDHN", DbType="Float")]
		public System.Nullable<double> TONGDHN
		{
			get
			{
				return this._TONGDHN;
			}
			set
			{
				if ((this._TONGDHN != value))
				{
					this.OnTONGDHNChanging(value);
					this.SendPropertyChanging();
					this._TONGDHN = value;
					this.SendPropertyChanged("TONGDHN");
					this.OnTONGDHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KN_DHN", DbType="Float")]
		public System.Nullable<double> KN_DHN
		{
			get
			{
				return this._KN_DHN;
			}
			set
			{
				if ((this._KN_DHN != value))
				{
					this.OnKN_DHNChanging(value);
					this.SendPropertyChanging();
					this._KN_DHN = value;
					this.SendPropertyChanged("KN_DHN");
					this.OnKN_DHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KN_SANLUONG", DbType="Float")]
		public System.Nullable<double> KN_SANLUONG
		{
			get
			{
				return this._KN_SANLUONG;
			}
			set
			{
				if ((this._KN_SANLUONG != value))
				{
					this.OnKN_SANLUONGChanging(value);
					this.SendPropertyChanging();
					this._KN_SANLUONG = value;
					this.SendPropertyChanged("KN_SANLUONG");
					this.OnKN_SANLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT_DHN", DbType="Float")]
		public System.Nullable<double> KT_DHN
		{
			get
			{
				return this._KT_DHN;
			}
			set
			{
				if ((this._KT_DHN != value))
				{
					this.OnKT_DHNChanging(value);
					this.SendPropertyChanging();
					this._KT_DHN = value;
					this.SendPropertyChanged("KT_DHN");
					this.OnKT_DHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT_SANLUONG", DbType="Float")]
		public System.Nullable<double> KT_SANLUONG
		{
			get
			{
				return this._KT_SANLUONG;
			}
			set
			{
				if ((this._KT_SANLUONG != value))
				{
					this.OnKT_SANLUONGChanging(value);
					this.SendPropertyChanging();
					this._KT_SANLUONG = value;
					this.SendPropertyChanged("KT_SANLUONG");
					this.OnKT_SANLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGIAM_DHN", DbType="Float")]
		public System.Nullable<double> TANGIAM_DHN
		{
			get
			{
				return this._TANGIAM_DHN;
			}
			set
			{
				if ((this._TANGIAM_DHN != value))
				{
					this.OnTANGIAM_DHNChanging(value);
					this.SendPropertyChanging();
					this._TANGIAM_DHN = value;
					this.SendPropertyChanged("TANGIAM_DHN");
					this.OnTANGIAM_DHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGIAM_SANLUONG", DbType="Float")]
		public System.Nullable<double> TANGIAM_SANLUONG
		{
			get
			{
				return this._TANGIAM_SANLUONG;
			}
			set
			{
				if ((this._TANGIAM_SANLUONG != value))
				{
					this.OnTANGIAM_SANLUONGChanging(value);
					this.SendPropertyChanging();
					this._TANGIAM_SANLUONG = value;
					this.SendPropertyChanged("TANGIAM_SANLUONG");
					this.OnTANGIAM_SANLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NT_DHN", DbType="Float")]
		public System.Nullable<double> NT_DHN
		{
			get
			{
				return this._NT_DHN;
			}
			set
			{
				if ((this._NT_DHN != value))
				{
					this.OnNT_DHNChanging(value);
					this.SendPropertyChanging();
					this._NT_DHN = value;
					this.SendPropertyChanged("NT_DHN");
					this.OnNT_DHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NT_SANLUONG", DbType="Float")]
		public System.Nullable<double> NT_SANLUONG
		{
			get
			{
				return this._NT_SANLUONG;
			}
			set
			{
				if ((this._NT_SANLUONG != value))
				{
					this.OnNT_SANLUONGChanging(value);
					this.SendPropertyChanging();
					this._NT_SANLUONG = value;
					this.SendPropertyChanged("NT_SANLUONG");
					this.OnNT_SANLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NT_TANGIAM_DHN", DbType="Float")]
		public System.Nullable<double> NT_TANGIAM_DHN
		{
			get
			{
				return this._NT_TANGIAM_DHN;
			}
			set
			{
				if ((this._NT_TANGIAM_DHN != value))
				{
					this.OnNT_TANGIAM_DHNChanging(value);
					this.SendPropertyChanging();
					this._NT_TANGIAM_DHN = value;
					this.SendPropertyChanged("NT_TANGIAM_DHN");
					this.OnNT_TANGIAM_DHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NT_TANGIAM_SANLUONG", DbType="Float")]
		public System.Nullable<double> NT_TANGIAM_SANLUONG
		{
			get
			{
				return this._NT_TANGIAM_SANLUONG;
			}
			set
			{
				if ((this._NT_TANGIAM_SANLUONG != value))
				{
					this.OnNT_TANGIAM_SANLUONGChanging(value);
					this.SendPropertyChanging();
					this._NT_TANGIAM_SANLUONG = value;
					this.SendPropertyChanged("NT_TANGIAM_SANLUONG");
					this.OnNT_TANGIAM_SANLUONGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYS_USERS")]
	public partial class SYS_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private string _FULLNAME;
		
		private string _ROLEID;
		
		private System.Nullable<bool> _ENABLED;
		
		private System.Nullable<int> _CAP;
		
		private string _MAPHONG;
		
		private string _TODS;
		
		private string _GIOIHAN;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _MODIFYBY;
		
		private System.Nullable<System.DateTime> _MODIFYDATE;
		
		private System.Nullable<bool> _DUYET;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnFULLNAMEChanging(string value);
    partial void OnFULLNAMEChanged();
    partial void OnROLEIDChanging(string value);
    partial void OnROLEIDChanged();
    partial void OnENABLEDChanging(System.Nullable<bool> value);
    partial void OnENABLEDChanged();
    partial void OnCAPChanging(System.Nullable<int> value);
    partial void OnCAPChanged();
    partial void OnMAPHONGChanging(string value);
    partial void OnMAPHONGChanged();
    partial void OnTODSChanging(string value);
    partial void OnTODSChanged();
    partial void OnGIOIHANChanging(string value);
    partial void OnGIOIHANChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnMODIFYBYChanging(string value);
    partial void OnMODIFYBYChanged();
    partial void OnMODIFYDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFYDATEChanged();
    partial void OnDUYETChanging(System.Nullable<bool> value);
    partial void OnDUYETChanged();
    #endregion
		
		public SYS_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="NVarChar(50)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this.OnFULLNAMEChanging(value);
					this.SendPropertyChanging();
					this._FULLNAME = value;
					this.SendPropertyChanged("FULLNAME");
					this.OnFULLNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLEID", DbType="VarChar(5)")]
		public string ROLEID
		{
			get
			{
				return this._ROLEID;
			}
			set
			{
				if ((this._ROLEID != value))
				{
					this.OnROLEIDChanging(value);
					this.SendPropertyChanging();
					this._ROLEID = value;
					this.SendPropertyChanged("ROLEID");
					this.OnROLEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENABLED", DbType="Bit")]
		public System.Nullable<bool> ENABLED
		{
			get
			{
				return this._ENABLED;
			}
			set
			{
				if ((this._ENABLED != value))
				{
					this.OnENABLEDChanging(value);
					this.SendPropertyChanging();
					this._ENABLED = value;
					this.SendPropertyChanged("ENABLED");
					this.OnENABLEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAP", DbType="Int")]
		public System.Nullable<int> CAP
		{
			get
			{
				return this._CAP;
			}
			set
			{
				if ((this._CAP != value))
				{
					this.OnCAPChanging(value);
					this.SendPropertyChanging();
					this._CAP = value;
					this.SendPropertyChanged("CAP");
					this.OnCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHONG", DbType="VarChar(20)")]
		public string MAPHONG
		{
			get
			{
				return this._MAPHONG;
			}
			set
			{
				if ((this._MAPHONG != value))
				{
					this.OnMAPHONGChanging(value);
					this.SendPropertyChanging();
					this._MAPHONG = value;
					this.SendPropertyChanged("MAPHONG");
					this.OnMAPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TODS", DbType="VarChar(20)")]
		public string TODS
		{
			get
			{
				return this._TODS;
			}
			set
			{
				if ((this._TODS != value))
				{
					this.OnTODSChanging(value);
					this.SendPropertyChanging();
					this._TODS = value;
					this.SendPropertyChanged("TODS");
					this.OnTODSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOIHAN", DbType="NVarChar(MAX)")]
		public string GIOIHAN
		{
			get
			{
				return this._GIOIHAN;
			}
			set
			{
				if ((this._GIOIHAN != value))
				{
					this.OnGIOIHANChanging(value);
					this.SendPropertyChanging();
					this._GIOIHAN = value;
					this.SendPropertyChanged("GIOIHAN");
					this.OnGIOIHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="VarChar(50)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYBY", DbType="VarChar(50)")]
		public string MODIFYBY
		{
			get
			{
				return this._MODIFYBY;
			}
			set
			{
				if ((this._MODIFYBY != value))
				{
					this.OnMODIFYBYChanging(value);
					this.SendPropertyChanging();
					this._MODIFYBY = value;
					this.SendPropertyChanged("MODIFYBY");
					this.OnMODIFYBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFYDATE
		{
			get
			{
				return this._MODIFYDATE;
			}
			set
			{
				if ((this._MODIFYDATE != value))
				{
					this.OnMODIFYDATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFYDATE = value;
					this.SendPropertyChanged("MODIFYDATE");
					this.OnMODIFYDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUYET", DbType="Bit")]
		public System.Nullable<bool> DUYET
		{
			get
			{
				return this._DUYET;
			}
			set
			{
				if ((this._DUYET != value))
				{
					this.OnDUYETChanging(value);
					this.SendPropertyChanging();
					this._DUYET = value;
					this.SendPropertyChanged("DUYET");
					this.OnDUYETChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_DULIEUKHACHHANG")]
	public partial class TB_DULIEUKHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KHU;
		
		private string _DOT;
		
		private string _CUON_GCS;
		
		private string _CUON_STT;
		
		private string _LOTRINH;
		
		private string _DANHBO;
		
		private string _NGAYGANDH;
		
		private string _HOPDONG;
		
		private string _HOTEN;
		
		private string _SONHA;
		
		private string _TENDUONG;
		
		private string _PHUONG;
		
		private string _QUAN;
		
		private string _CHUKY;
		
		private string _CODE;
		
		private string _CODEFU;
		
		private string _GIABIEU;
		
		private string _DINHMUC;
		
		private string _SH;
		
		private string _HCSN;
		
		private string _SX;
		
		private string _DV;
		
		private string _CODH;
		
		private string _HIEUDH;
		
		private string _SOTHANDH;
		
		private string _CAP;
		
		private string _CHITHAN;
		
		private string _CHIGOC;
		
		private string _VITRIDHN;
		
		private string _SODHN;
		
		private System.Nullable<System.DateTime> _NGAYTHAY;
		
		private System.Nullable<System.DateTime> _NGAYKIEMDINH;
		
		private string _MSTHUE;
		
		private string _SOHO;
		
		private string _CHISOKYTRUOC;
		
		private System.Nullable<bool> _BAOTHAY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _MODIFYDATE;
		
		private string _MODIFYBY;
		
		private System.Nullable<int> _KY;
		
		private System.Nullable<int> _NAM;
		
		private string _DIENTHOAI;
		
		private System.Nullable<int> _KY_;
		
		private string _MADMA;
		
		private System.Nullable<int> _CHUKYDS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKHUChanging(string value);
    partial void OnKHUChanged();
    partial void OnDOTChanging(string value);
    partial void OnDOTChanged();
    partial void OnCUON_GCSChanging(string value);
    partial void OnCUON_GCSChanged();
    partial void OnCUON_STTChanging(string value);
    partial void OnCUON_STTChanged();
    partial void OnLOTRINHChanging(string value);
    partial void OnLOTRINHChanged();
    partial void OnDANHBOChanging(string value);
    partial void OnDANHBOChanged();
    partial void OnNGAYGANDHChanging(string value);
    partial void OnNGAYGANDHChanged();
    partial void OnHOPDONGChanging(string value);
    partial void OnHOPDONGChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnSONHAChanging(string value);
    partial void OnSONHAChanged();
    partial void OnTENDUONGChanging(string value);
    partial void OnTENDUONGChanged();
    partial void OnPHUONGChanging(string value);
    partial void OnPHUONGChanged();
    partial void OnQUANChanging(string value);
    partial void OnQUANChanged();
    partial void OnCHUKYChanging(string value);
    partial void OnCHUKYChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnCODEFUChanging(string value);
    partial void OnCODEFUChanged();
    partial void OnGIABIEUChanging(string value);
    partial void OnGIABIEUChanged();
    partial void OnDINHMUCChanging(string value);
    partial void OnDINHMUCChanged();
    partial void OnSHChanging(string value);
    partial void OnSHChanged();
    partial void OnHCSNChanging(string value);
    partial void OnHCSNChanged();
    partial void OnSXChanging(string value);
    partial void OnSXChanged();
    partial void OnDVChanging(string value);
    partial void OnDVChanged();
    partial void OnCODHChanging(string value);
    partial void OnCODHChanged();
    partial void OnHIEUDHChanging(string value);
    partial void OnHIEUDHChanged();
    partial void OnSOTHANDHChanging(string value);
    partial void OnSOTHANDHChanged();
    partial void OnCAPChanging(string value);
    partial void OnCAPChanged();
    partial void OnCHITHANChanging(string value);
    partial void OnCHITHANChanged();
    partial void OnCHIGOCChanging(string value);
    partial void OnCHIGOCChanged();
    partial void OnVITRIDHNChanging(string value);
    partial void OnVITRIDHNChanged();
    partial void OnSODHNChanging(string value);
    partial void OnSODHNChanged();
    partial void OnNGAYTHAYChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHAYChanged();
    partial void OnNGAYKIEMDINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYKIEMDINHChanged();
    partial void OnMSTHUEChanging(string value);
    partial void OnMSTHUEChanged();
    partial void OnSOHOChanging(string value);
    partial void OnSOHOChanged();
    partial void OnCHISOKYTRUOCChanging(string value);
    partial void OnCHISOKYTRUOCChanged();
    partial void OnBAOTHAYChanging(System.Nullable<bool> value);
    partial void OnBAOTHAYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnMODIFYDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFYDATEChanged();
    partial void OnMODIFYBYChanging(string value);
    partial void OnMODIFYBYChanged();
    partial void OnKYChanging(System.Nullable<int> value);
    partial void OnKYChanged();
    partial void OnNAMChanging(System.Nullable<int> value);
    partial void OnNAMChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnKY_Changing(System.Nullable<int> value);
    partial void OnKY_Changed();
    partial void OnMADMAChanging(string value);
    partial void OnMADMAChanged();
    partial void OnCHUKYDSChanging(System.Nullable<int> value);
    partial void OnCHUKYDSChanged();
    #endregion
		
		public TB_DULIEUKHACHHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHU", DbType="VarChar(255)")]
		public string KHU
		{
			get
			{
				return this._KHU;
			}
			set
			{
				if ((this._KHU != value))
				{
					this.OnKHUChanging(value);
					this.SendPropertyChanging();
					this._KHU = value;
					this.SendPropertyChanged("KHU");
					this.OnKHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOT", DbType="VarChar(255)")]
		public string DOT
		{
			get
			{
				return this._DOT;
			}
			set
			{
				if ((this._DOT != value))
				{
					this.OnDOTChanging(value);
					this.SendPropertyChanging();
					this._DOT = value;
					this.SendPropertyChanged("DOT");
					this.OnDOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUON_GCS", DbType="NVarChar(MAX)")]
		public string CUON_GCS
		{
			get
			{
				return this._CUON_GCS;
			}
			set
			{
				if ((this._CUON_GCS != value))
				{
					this.OnCUON_GCSChanging(value);
					this.SendPropertyChanging();
					this._CUON_GCS = value;
					this.SendPropertyChanged("CUON_GCS");
					this.OnCUON_GCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUON_STT", DbType="NVarChar(MAX)")]
		public string CUON_STT
		{
			get
			{
				return this._CUON_STT;
			}
			set
			{
				if ((this._CUON_STT != value))
				{
					this.OnCUON_STTChanging(value);
					this.SendPropertyChanging();
					this._CUON_STT = value;
					this.SendPropertyChanged("CUON_STT");
					this.OnCUON_STTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOTRINH", DbType="NVarChar(100)")]
		public string LOTRINH
		{
			get
			{
				return this._LOTRINH;
			}
			set
			{
				if ((this._LOTRINH != value))
				{
					this.OnLOTRINHChanging(value);
					this.SendPropertyChanging();
					this._LOTRINH = value;
					this.SendPropertyChanged("LOTRINH");
					this.OnLOTRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANHBO", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DANHBO
		{
			get
			{
				return this._DANHBO;
			}
			set
			{
				if ((this._DANHBO != value))
				{
					this.OnDANHBOChanging(value);
					this.SendPropertyChanging();
					this._DANHBO = value;
					this.SendPropertyChanged("DANHBO");
					this.OnDANHBOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGANDH", DbType="NVarChar(255)")]
		public string NGAYGANDH
		{
			get
			{
				return this._NGAYGANDH;
			}
			set
			{
				if ((this._NGAYGANDH != value))
				{
					this.OnNGAYGANDHChanging(value);
					this.SendPropertyChanging();
					this._NGAYGANDH = value;
					this.SendPropertyChanged("NGAYGANDH");
					this.OnNGAYGANDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOPDONG", DbType="VarChar(255)")]
		public string HOPDONG
		{
			get
			{
				return this._HOPDONG;
			}
			set
			{
				if ((this._HOPDONG != value))
				{
					this.OnHOPDONGChanging(value);
					this.SendPropertyChanging();
					this._HOPDONG = value;
					this.SendPropertyChanged("HOPDONG");
					this.OnHOPDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(MAX)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONHA", DbType="NVarChar(MAX)")]
		public string SONHA
		{
			get
			{
				return this._SONHA;
			}
			set
			{
				if ((this._SONHA != value))
				{
					this.OnSONHAChanging(value);
					this.SendPropertyChanging();
					this._SONHA = value;
					this.SendPropertyChanged("SONHA");
					this.OnSONHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDUONG", DbType="NVarChar(MAX)")]
		public string TENDUONG
		{
			get
			{
				return this._TENDUONG;
			}
			set
			{
				if ((this._TENDUONG != value))
				{
					this.OnTENDUONGChanging(value);
					this.SendPropertyChanging();
					this._TENDUONG = value;
					this.SendPropertyChanged("TENDUONG");
					this.OnTENDUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHUONG", DbType="NVarChar(255)")]
		public string PHUONG
		{
			get
			{
				return this._PHUONG;
			}
			set
			{
				if ((this._PHUONG != value))
				{
					this.OnPHUONGChanging(value);
					this.SendPropertyChanging();
					this._PHUONG = value;
					this.SendPropertyChanged("PHUONG");
					this.OnPHUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUAN", DbType="NVarChar(255)")]
		public string QUAN
		{
			get
			{
				return this._QUAN;
			}
			set
			{
				if ((this._QUAN != value))
				{
					this.OnQUANChanging(value);
					this.SendPropertyChanging();
					this._QUAN = value;
					this.SendPropertyChanged("QUAN");
					this.OnQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUKY", DbType="NVarChar(255)")]
		public string CHUKY
		{
			get
			{
				return this._CHUKY;
			}
			set
			{
				if ((this._CHUKY != value))
				{
					this.OnCHUKYChanging(value);
					this.SendPropertyChanging();
					this._CHUKY = value;
					this.SendPropertyChanged("CHUKY");
					this.OnCHUKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(255)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEFU", DbType="NVarChar(255)")]
		public string CODEFU
		{
			get
			{
				return this._CODEFU;
			}
			set
			{
				if ((this._CODEFU != value))
				{
					this.OnCODEFUChanging(value);
					this.SendPropertyChanging();
					this._CODEFU = value;
					this.SendPropertyChanged("CODEFU");
					this.OnCODEFUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABIEU", DbType="VarChar(50)")]
		public string GIABIEU
		{
			get
			{
				return this._GIABIEU;
			}
			set
			{
				if ((this._GIABIEU != value))
				{
					this.OnGIABIEUChanging(value);
					this.SendPropertyChanging();
					this._GIABIEU = value;
					this.SendPropertyChanged("GIABIEU");
					this.OnGIABIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DINHMUC", DbType="VarChar(50)")]
		public string DINHMUC
		{
			get
			{
				return this._DINHMUC;
			}
			set
			{
				if ((this._DINHMUC != value))
				{
					this.OnDINHMUCChanging(value);
					this.SendPropertyChanging();
					this._DINHMUC = value;
					this.SendPropertyChanged("DINHMUC");
					this.OnDINHMUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SH", DbType="NVarChar(255)")]
		public string SH
		{
			get
			{
				return this._SH;
			}
			set
			{
				if ((this._SH != value))
				{
					this.OnSHChanging(value);
					this.SendPropertyChanging();
					this._SH = value;
					this.SendPropertyChanged("SH");
					this.OnSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSN", DbType="NVarChar(255)")]
		public string HCSN
		{
			get
			{
				return this._HCSN;
			}
			set
			{
				if ((this._HCSN != value))
				{
					this.OnHCSNChanging(value);
					this.SendPropertyChanging();
					this._HCSN = value;
					this.SendPropertyChanged("HCSN");
					this.OnHCSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SX", DbType="NVarChar(255)")]
		public string SX
		{
			get
			{
				return this._SX;
			}
			set
			{
				if ((this._SX != value))
				{
					this.OnSXChanging(value);
					this.SendPropertyChanging();
					this._SX = value;
					this.SendPropertyChanged("SX");
					this.OnSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV", DbType="NVarChar(255)")]
		public string DV
		{
			get
			{
				return this._DV;
			}
			set
			{
				if ((this._DV != value))
				{
					this.OnDVChanging(value);
					this.SendPropertyChanging();
					this._DV = value;
					this.SendPropertyChanged("DV");
					this.OnDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODH", DbType="NVarChar(255)")]
		public string CODH
		{
			get
			{
				return this._CODH;
			}
			set
			{
				if ((this._CODH != value))
				{
					this.OnCODHChanging(value);
					this.SendPropertyChanging();
					this._CODH = value;
					this.SendPropertyChanged("CODH");
					this.OnCODHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEUDH", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string HIEUDH
		{
			get
			{
				return this._HIEUDH;
			}
			set
			{
				if ((this._HIEUDH != value))
				{
					this.OnHIEUDHChanging(value);
					this.SendPropertyChanging();
					this._HIEUDH = value;
					this.SendPropertyChanged("HIEUDH");
					this.OnHIEUDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTHANDH", DbType="NVarChar(255)")]
		public string SOTHANDH
		{
			get
			{
				return this._SOTHANDH;
			}
			set
			{
				if ((this._SOTHANDH != value))
				{
					this.OnSOTHANDHChanging(value);
					this.SendPropertyChanging();
					this._SOTHANDH = value;
					this.SendPropertyChanged("SOTHANDH");
					this.OnSOTHANDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAP", DbType="NVarChar(255)")]
		public string CAP
		{
			get
			{
				return this._CAP;
			}
			set
			{
				if ((this._CAP != value))
				{
					this.OnCAPChanging(value);
					this.SendPropertyChanging();
					this._CAP = value;
					this.SendPropertyChanged("CAP");
					this.OnCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITHAN", DbType="NVarChar(255)")]
		public string CHITHAN
		{
			get
			{
				return this._CHITHAN;
			}
			set
			{
				if ((this._CHITHAN != value))
				{
					this.OnCHITHANChanging(value);
					this.SendPropertyChanging();
					this._CHITHAN = value;
					this.SendPropertyChanged("CHITHAN");
					this.OnCHITHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHIGOC", DbType="NVarChar(255)")]
		public string CHIGOC
		{
			get
			{
				return this._CHIGOC;
			}
			set
			{
				if ((this._CHIGOC != value))
				{
					this.OnCHIGOCChanging(value);
					this.SendPropertyChanging();
					this._CHIGOC = value;
					this.SendPropertyChanged("CHIGOC");
					this.OnCHIGOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VITRIDHN", DbType="NVarChar(255)")]
		public string VITRIDHN
		{
			get
			{
				return this._VITRIDHN;
			}
			set
			{
				if ((this._VITRIDHN != value))
				{
					this.OnVITRIDHNChanging(value);
					this.SendPropertyChanging();
					this._VITRIDHN = value;
					this.SendPropertyChanged("VITRIDHN");
					this.OnVITRIDHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODHN", DbType="NVarChar(255)")]
		public string SODHN
		{
			get
			{
				return this._SODHN;
			}
			set
			{
				if ((this._SODHN != value))
				{
					this.OnSODHNChanging(value);
					this.SendPropertyChanging();
					this._SODHN = value;
					this.SendPropertyChanged("SODHN");
					this.OnSODHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHAY", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTHAY
		{
			get
			{
				return this._NGAYTHAY;
			}
			set
			{
				if ((this._NGAYTHAY != value))
				{
					this.OnNGAYTHAYChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHAY = value;
					this.SendPropertyChanged("NGAYTHAY");
					this.OnNGAYTHAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKIEMDINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYKIEMDINH
		{
			get
			{
				return this._NGAYKIEMDINH;
			}
			set
			{
				if ((this._NGAYKIEMDINH != value))
				{
					this.OnNGAYKIEMDINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYKIEMDINH = value;
					this.SendPropertyChanged("NGAYKIEMDINH");
					this.OnNGAYKIEMDINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSTHUE", DbType="NVarChar(255)")]
		public string MSTHUE
		{
			get
			{
				return this._MSTHUE;
			}
			set
			{
				if ((this._MSTHUE != value))
				{
					this.OnMSTHUEChanging(value);
					this.SendPropertyChanging();
					this._MSTHUE = value;
					this.SendPropertyChanged("MSTHUE");
					this.OnMSTHUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOHO", DbType="NVarChar(255)")]
		public string SOHO
		{
			get
			{
				return this._SOHO;
			}
			set
			{
				if ((this._SOHO != value))
				{
					this.OnSOHOChanging(value);
					this.SendPropertyChanging();
					this._SOHO = value;
					this.SendPropertyChanged("SOHO");
					this.OnSOHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHISOKYTRUOC", DbType="NVarChar(255)")]
		public string CHISOKYTRUOC
		{
			get
			{
				return this._CHISOKYTRUOC;
			}
			set
			{
				if ((this._CHISOKYTRUOC != value))
				{
					this.OnCHISOKYTRUOCChanging(value);
					this.SendPropertyChanging();
					this._CHISOKYTRUOC = value;
					this.SendPropertyChanged("CHISOKYTRUOC");
					this.OnCHISOKYTRUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAOTHAY", DbType="Bit")]
		public System.Nullable<bool> BAOTHAY
		{
			get
			{
				return this._BAOTHAY;
			}
			set
			{
				if ((this._BAOTHAY != value))
				{
					this.OnBAOTHAYChanging(value);
					this.SendPropertyChanging();
					this._BAOTHAY = value;
					this.SendPropertyChanged("BAOTHAY");
					this.OnBAOTHAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="NVarChar(100)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFYDATE
		{
			get
			{
				return this._MODIFYDATE;
			}
			set
			{
				if ((this._MODIFYDATE != value))
				{
					this.OnMODIFYDATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFYDATE = value;
					this.SendPropertyChanged("MODIFYDATE");
					this.OnMODIFYDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYBY", DbType="NVarChar(100)")]
		public string MODIFYBY
		{
			get
			{
				return this._MODIFYBY;
			}
			set
			{
				if ((this._MODIFYBY != value))
				{
					this.OnMODIFYBYChanging(value);
					this.SendPropertyChanging();
					this._MODIFYBY = value;
					this.SendPropertyChanged("MODIFYBY");
					this.OnMODIFYBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KY", DbType="Int")]
		public System.Nullable<int> KY
		{
			get
			{
				return this._KY;
			}
			set
			{
				if ((this._KY != value))
				{
					this.OnKYChanging(value);
					this.SendPropertyChanging();
					this._KY = value;
					this.SendPropertyChanged("KY");
					this.OnKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAM", DbType="Int")]
		public System.Nullable<int> NAM
		{
			get
			{
				return this._NAM;
			}
			set
			{
				if ((this._NAM != value))
				{
					this.OnNAMChanging(value);
					this.SendPropertyChanging();
					this._NAM = value;
					this.SendPropertyChanged("NAM");
					this.OnNAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NVarChar(100)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KY_", DbType="Int")]
		public System.Nullable<int> KY_
		{
			get
			{
				return this._KY_;
			}
			set
			{
				if ((this._KY_ != value))
				{
					this.OnKY_Changing(value);
					this.SendPropertyChanging();
					this._KY_ = value;
					this.SendPropertyChanged("KY_");
					this.OnKY_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADMA", DbType="VarChar(255)")]
		public string MADMA
		{
			get
			{
				return this._MADMA;
			}
			set
			{
				if ((this._MADMA != value))
				{
					this.OnMADMAChanging(value);
					this.SendPropertyChanging();
					this._MADMA = value;
					this.SendPropertyChanged("MADMA");
					this.OnMADMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUKYDS", DbType="Int")]
		public System.Nullable<int> CHUKYDS
		{
			get
			{
				return this._CHUKYDS;
			}
			set
			{
				if ((this._CHUKYDS != value))
				{
					this.OnCHUKYDSChanging(value);
					this.SendPropertyChanging();
					this._CHUKYDS = value;
					this.SendPropertyChanged("CHUKYDS");
					this.OnCHUKYDSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_DULIEUKHACHHANG_HUYDB")]
	public partial class TB_DULIEUKHACHHANG_HUYDB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KHU;
		
		private string _DOT;
		
		private string _CUON_GCS;
		
		private string _CUON_STT;
		
		private string _LOTRINH;
		
		private string _DANHBO;
		
		private string _NGAYGANDH;
		
		private string _HOPDONG;
		
		private string _HOTEN;
		
		private string _SONHA;
		
		private string _TENDUONG;
		
		private string _PHUONG;
		
		private string _QUAN;
		
		private string _CHUKY;
		
		private string _CODE;
		
		private string _CODEFU;
		
		private string _GIABIEU;
		
		private string _DINHMUC;
		
		private string _SH;
		
		private string _HCSN;
		
		private string _SX;
		
		private string _DV;
		
		private string _CODH;
		
		private string _HIEUDH;
		
		private string _CAP;
		
		private string _SOTHANDH;
		
		private string _CHITHAN;
		
		private string _CHIGOC;
		
		private string _VITRIDHN;
		
		private System.Nullable<System.DateTime> _NGAYTHAY;
		
		private System.Nullable<System.DateTime> _NGAYKIEMDINH;
		
		private string _SODHN;
		
		private string _MSTHUE;
		
		private string _SOHO;
		
		private string _CHISOKYTRUOC;
		
		private string _SOPHIEU;
		
		private System.Nullable<System.DateTime> _NGAYHUY;
		
		private string _HIEULUCHUY;
		
		private string _NGUYENNHAN;
		
		private string _GHICHU;
		
		private System.Nullable<bool> _TAILAPDB;
		
		private System.Nullable<System.DateTime> _NGAYTAILAP;
		
		private string _TL_SOPHIEU;
		
		private string _TL_HIEULUC;
		
		private string _TL_DOT;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _MODIFYDATE;
		
		private string _MODIFYBY;
		
		private string _MADMA;
		
		private System.Nullable<int> _CHUKYDS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKHUChanging(string value);
    partial void OnKHUChanged();
    partial void OnDOTChanging(string value);
    partial void OnDOTChanged();
    partial void OnCUON_GCSChanging(string value);
    partial void OnCUON_GCSChanged();
    partial void OnCUON_STTChanging(string value);
    partial void OnCUON_STTChanged();
    partial void OnLOTRINHChanging(string value);
    partial void OnLOTRINHChanged();
    partial void OnDANHBOChanging(string value);
    partial void OnDANHBOChanged();
    partial void OnNGAYGANDHChanging(string value);
    partial void OnNGAYGANDHChanged();
    partial void OnHOPDONGChanging(string value);
    partial void OnHOPDONGChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnSONHAChanging(string value);
    partial void OnSONHAChanged();
    partial void OnTENDUONGChanging(string value);
    partial void OnTENDUONGChanged();
    partial void OnPHUONGChanging(string value);
    partial void OnPHUONGChanged();
    partial void OnQUANChanging(string value);
    partial void OnQUANChanged();
    partial void OnCHUKYChanging(string value);
    partial void OnCHUKYChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnCODEFUChanging(string value);
    partial void OnCODEFUChanged();
    partial void OnGIABIEUChanging(string value);
    partial void OnGIABIEUChanged();
    partial void OnDINHMUCChanging(string value);
    partial void OnDINHMUCChanged();
    partial void OnSHChanging(string value);
    partial void OnSHChanged();
    partial void OnHCSNChanging(string value);
    partial void OnHCSNChanged();
    partial void OnSXChanging(string value);
    partial void OnSXChanged();
    partial void OnDVChanging(string value);
    partial void OnDVChanged();
    partial void OnCODHChanging(string value);
    partial void OnCODHChanged();
    partial void OnHIEUDHChanging(string value);
    partial void OnHIEUDHChanged();
    partial void OnCAPChanging(string value);
    partial void OnCAPChanged();
    partial void OnSOTHANDHChanging(string value);
    partial void OnSOTHANDHChanged();
    partial void OnCHITHANChanging(string value);
    partial void OnCHITHANChanged();
    partial void OnCHIGOCChanging(string value);
    partial void OnCHIGOCChanged();
    partial void OnVITRIDHNChanging(string value);
    partial void OnVITRIDHNChanged();
    partial void OnNGAYTHAYChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHAYChanged();
    partial void OnNGAYKIEMDINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYKIEMDINHChanged();
    partial void OnSODHNChanging(string value);
    partial void OnSODHNChanged();
    partial void OnMSTHUEChanging(string value);
    partial void OnMSTHUEChanged();
    partial void OnSOHOChanging(string value);
    partial void OnSOHOChanged();
    partial void OnCHISOKYTRUOCChanging(string value);
    partial void OnCHISOKYTRUOCChanged();
    partial void OnSOPHIEUChanging(string value);
    partial void OnSOPHIEUChanged();
    partial void OnNGAYHUYChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYHUYChanged();
    partial void OnHIEULUCHUYChanging(string value);
    partial void OnHIEULUCHUYChanged();
    partial void OnNGUYENNHANChanging(string value);
    partial void OnNGUYENNHANChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    partial void OnTAILAPDBChanging(System.Nullable<bool> value);
    partial void OnTAILAPDBChanged();
    partial void OnNGAYTAILAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAILAPChanged();
    partial void OnTL_SOPHIEUChanging(string value);
    partial void OnTL_SOPHIEUChanged();
    partial void OnTL_HIEULUCChanging(string value);
    partial void OnTL_HIEULUCChanged();
    partial void OnTL_DOTChanging(string value);
    partial void OnTL_DOTChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnMODIFYDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFYDATEChanged();
    partial void OnMODIFYBYChanging(string value);
    partial void OnMODIFYBYChanged();
    partial void OnMADMAChanging(string value);
    partial void OnMADMAChanged();
    partial void OnCHUKYDSChanging(System.Nullable<int> value);
    partial void OnCHUKYDSChanged();
    #endregion
		
		public TB_DULIEUKHACHHANG_HUYDB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHU", DbType="VarChar(255)")]
		public string KHU
		{
			get
			{
				return this._KHU;
			}
			set
			{
				if ((this._KHU != value))
				{
					this.OnKHUChanging(value);
					this.SendPropertyChanging();
					this._KHU = value;
					this.SendPropertyChanged("KHU");
					this.OnKHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOT", DbType="VarChar(255)")]
		public string DOT
		{
			get
			{
				return this._DOT;
			}
			set
			{
				if ((this._DOT != value))
				{
					this.OnDOTChanging(value);
					this.SendPropertyChanging();
					this._DOT = value;
					this.SendPropertyChanged("DOT");
					this.OnDOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUON_GCS", DbType="NVarChar(MAX)")]
		public string CUON_GCS
		{
			get
			{
				return this._CUON_GCS;
			}
			set
			{
				if ((this._CUON_GCS != value))
				{
					this.OnCUON_GCSChanging(value);
					this.SendPropertyChanging();
					this._CUON_GCS = value;
					this.SendPropertyChanged("CUON_GCS");
					this.OnCUON_GCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUON_STT", DbType="NVarChar(MAX)")]
		public string CUON_STT
		{
			get
			{
				return this._CUON_STT;
			}
			set
			{
				if ((this._CUON_STT != value))
				{
					this.OnCUON_STTChanging(value);
					this.SendPropertyChanging();
					this._CUON_STT = value;
					this.SendPropertyChanged("CUON_STT");
					this.OnCUON_STTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOTRINH", DbType="VarChar(255)")]
		public string LOTRINH
		{
			get
			{
				return this._LOTRINH;
			}
			set
			{
				if ((this._LOTRINH != value))
				{
					this.OnLOTRINHChanging(value);
					this.SendPropertyChanging();
					this._LOTRINH = value;
					this.SendPropertyChanged("LOTRINH");
					this.OnLOTRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANHBO", DbType="VarChar(255)")]
		public string DANHBO
		{
			get
			{
				return this._DANHBO;
			}
			set
			{
				if ((this._DANHBO != value))
				{
					this.OnDANHBOChanging(value);
					this.SendPropertyChanging();
					this._DANHBO = value;
					this.SendPropertyChanged("DANHBO");
					this.OnDANHBOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGANDH", DbType="NVarChar(255)")]
		public string NGAYGANDH
		{
			get
			{
				return this._NGAYGANDH;
			}
			set
			{
				if ((this._NGAYGANDH != value))
				{
					this.OnNGAYGANDHChanging(value);
					this.SendPropertyChanging();
					this._NGAYGANDH = value;
					this.SendPropertyChanged("NGAYGANDH");
					this.OnNGAYGANDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOPDONG", DbType="VarChar(255)")]
		public string HOPDONG
		{
			get
			{
				return this._HOPDONG;
			}
			set
			{
				if ((this._HOPDONG != value))
				{
					this.OnHOPDONGChanging(value);
					this.SendPropertyChanging();
					this._HOPDONG = value;
					this.SendPropertyChanged("HOPDONG");
					this.OnHOPDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(MAX)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONHA", DbType="NVarChar(MAX)")]
		public string SONHA
		{
			get
			{
				return this._SONHA;
			}
			set
			{
				if ((this._SONHA != value))
				{
					this.OnSONHAChanging(value);
					this.SendPropertyChanging();
					this._SONHA = value;
					this.SendPropertyChanged("SONHA");
					this.OnSONHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDUONG", DbType="NVarChar(MAX)")]
		public string TENDUONG
		{
			get
			{
				return this._TENDUONG;
			}
			set
			{
				if ((this._TENDUONG != value))
				{
					this.OnTENDUONGChanging(value);
					this.SendPropertyChanging();
					this._TENDUONG = value;
					this.SendPropertyChanged("TENDUONG");
					this.OnTENDUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHUONG", DbType="NVarChar(255)")]
		public string PHUONG
		{
			get
			{
				return this._PHUONG;
			}
			set
			{
				if ((this._PHUONG != value))
				{
					this.OnPHUONGChanging(value);
					this.SendPropertyChanging();
					this._PHUONG = value;
					this.SendPropertyChanged("PHUONG");
					this.OnPHUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUAN", DbType="NVarChar(255)")]
		public string QUAN
		{
			get
			{
				return this._QUAN;
			}
			set
			{
				if ((this._QUAN != value))
				{
					this.OnQUANChanging(value);
					this.SendPropertyChanging();
					this._QUAN = value;
					this.SendPropertyChanged("QUAN");
					this.OnQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUKY", DbType="NVarChar(255)")]
		public string CHUKY
		{
			get
			{
				return this._CHUKY;
			}
			set
			{
				if ((this._CHUKY != value))
				{
					this.OnCHUKYChanging(value);
					this.SendPropertyChanging();
					this._CHUKY = value;
					this.SendPropertyChanged("CHUKY");
					this.OnCHUKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(255)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEFU", DbType="NVarChar(255)")]
		public string CODEFU
		{
			get
			{
				return this._CODEFU;
			}
			set
			{
				if ((this._CODEFU != value))
				{
					this.OnCODEFUChanging(value);
					this.SendPropertyChanging();
					this._CODEFU = value;
					this.SendPropertyChanged("CODEFU");
					this.OnCODEFUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABIEU", DbType="NVarChar(255)")]
		public string GIABIEU
		{
			get
			{
				return this._GIABIEU;
			}
			set
			{
				if ((this._GIABIEU != value))
				{
					this.OnGIABIEUChanging(value);
					this.SendPropertyChanging();
					this._GIABIEU = value;
					this.SendPropertyChanged("GIABIEU");
					this.OnGIABIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DINHMUC", DbType="NVarChar(255)")]
		public string DINHMUC
		{
			get
			{
				return this._DINHMUC;
			}
			set
			{
				if ((this._DINHMUC != value))
				{
					this.OnDINHMUCChanging(value);
					this.SendPropertyChanging();
					this._DINHMUC = value;
					this.SendPropertyChanged("DINHMUC");
					this.OnDINHMUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SH", DbType="NVarChar(255)")]
		public string SH
		{
			get
			{
				return this._SH;
			}
			set
			{
				if ((this._SH != value))
				{
					this.OnSHChanging(value);
					this.SendPropertyChanging();
					this._SH = value;
					this.SendPropertyChanged("SH");
					this.OnSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSN", DbType="NVarChar(255)")]
		public string HCSN
		{
			get
			{
				return this._HCSN;
			}
			set
			{
				if ((this._HCSN != value))
				{
					this.OnHCSNChanging(value);
					this.SendPropertyChanging();
					this._HCSN = value;
					this.SendPropertyChanged("HCSN");
					this.OnHCSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SX", DbType="NVarChar(255)")]
		public string SX
		{
			get
			{
				return this._SX;
			}
			set
			{
				if ((this._SX != value))
				{
					this.OnSXChanging(value);
					this.SendPropertyChanging();
					this._SX = value;
					this.SendPropertyChanged("SX");
					this.OnSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV", DbType="NVarChar(255)")]
		public string DV
		{
			get
			{
				return this._DV;
			}
			set
			{
				if ((this._DV != value))
				{
					this.OnDVChanging(value);
					this.SendPropertyChanging();
					this._DV = value;
					this.SendPropertyChanged("DV");
					this.OnDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODH", DbType="NVarChar(255)")]
		public string CODH
		{
			get
			{
				return this._CODH;
			}
			set
			{
				if ((this._CODH != value))
				{
					this.OnCODHChanging(value);
					this.SendPropertyChanging();
					this._CODH = value;
					this.SendPropertyChanged("CODH");
					this.OnCODHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEUDH", DbType="NVarChar(255)")]
		public string HIEUDH
		{
			get
			{
				return this._HIEUDH;
			}
			set
			{
				if ((this._HIEUDH != value))
				{
					this.OnHIEUDHChanging(value);
					this.SendPropertyChanging();
					this._HIEUDH = value;
					this.SendPropertyChanged("HIEUDH");
					this.OnHIEUDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAP", DbType="NVarChar(255)")]
		public string CAP
		{
			get
			{
				return this._CAP;
			}
			set
			{
				if ((this._CAP != value))
				{
					this.OnCAPChanging(value);
					this.SendPropertyChanging();
					this._CAP = value;
					this.SendPropertyChanged("CAP");
					this.OnCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTHANDH", DbType="NVarChar(255)")]
		public string SOTHANDH
		{
			get
			{
				return this._SOTHANDH;
			}
			set
			{
				if ((this._SOTHANDH != value))
				{
					this.OnSOTHANDHChanging(value);
					this.SendPropertyChanging();
					this._SOTHANDH = value;
					this.SendPropertyChanged("SOTHANDH");
					this.OnSOTHANDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITHAN", DbType="NVarChar(255)")]
		public string CHITHAN
		{
			get
			{
				return this._CHITHAN;
			}
			set
			{
				if ((this._CHITHAN != value))
				{
					this.OnCHITHANChanging(value);
					this.SendPropertyChanging();
					this._CHITHAN = value;
					this.SendPropertyChanged("CHITHAN");
					this.OnCHITHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHIGOC", DbType="NVarChar(255)")]
		public string CHIGOC
		{
			get
			{
				return this._CHIGOC;
			}
			set
			{
				if ((this._CHIGOC != value))
				{
					this.OnCHIGOCChanging(value);
					this.SendPropertyChanging();
					this._CHIGOC = value;
					this.SendPropertyChanged("CHIGOC");
					this.OnCHIGOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VITRIDHN", DbType="NVarChar(255)")]
		public string VITRIDHN
		{
			get
			{
				return this._VITRIDHN;
			}
			set
			{
				if ((this._VITRIDHN != value))
				{
					this.OnVITRIDHNChanging(value);
					this.SendPropertyChanging();
					this._VITRIDHN = value;
					this.SendPropertyChanged("VITRIDHN");
					this.OnVITRIDHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHAY", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTHAY
		{
			get
			{
				return this._NGAYTHAY;
			}
			set
			{
				if ((this._NGAYTHAY != value))
				{
					this.OnNGAYTHAYChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHAY = value;
					this.SendPropertyChanged("NGAYTHAY");
					this.OnNGAYTHAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKIEMDINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYKIEMDINH
		{
			get
			{
				return this._NGAYKIEMDINH;
			}
			set
			{
				if ((this._NGAYKIEMDINH != value))
				{
					this.OnNGAYKIEMDINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYKIEMDINH = value;
					this.SendPropertyChanged("NGAYKIEMDINH");
					this.OnNGAYKIEMDINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODHN", DbType="NVarChar(255)")]
		public string SODHN
		{
			get
			{
				return this._SODHN;
			}
			set
			{
				if ((this._SODHN != value))
				{
					this.OnSODHNChanging(value);
					this.SendPropertyChanging();
					this._SODHN = value;
					this.SendPropertyChanged("SODHN");
					this.OnSODHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSTHUE", DbType="NVarChar(255)")]
		public string MSTHUE
		{
			get
			{
				return this._MSTHUE;
			}
			set
			{
				if ((this._MSTHUE != value))
				{
					this.OnMSTHUEChanging(value);
					this.SendPropertyChanging();
					this._MSTHUE = value;
					this.SendPropertyChanged("MSTHUE");
					this.OnMSTHUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOHO", DbType="NVarChar(255)")]
		public string SOHO
		{
			get
			{
				return this._SOHO;
			}
			set
			{
				if ((this._SOHO != value))
				{
					this.OnSOHOChanging(value);
					this.SendPropertyChanging();
					this._SOHO = value;
					this.SendPropertyChanged("SOHO");
					this.OnSOHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHISOKYTRUOC", DbType="NVarChar(255)")]
		public string CHISOKYTRUOC
		{
			get
			{
				return this._CHISOKYTRUOC;
			}
			set
			{
				if ((this._CHISOKYTRUOC != value))
				{
					this.OnCHISOKYTRUOCChanging(value);
					this.SendPropertyChanging();
					this._CHISOKYTRUOC = value;
					this.SendPropertyChanged("CHISOKYTRUOC");
					this.OnCHISOKYTRUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOPHIEU", DbType="NVarChar(255)")]
		public string SOPHIEU
		{
			get
			{
				return this._SOPHIEU;
			}
			set
			{
				if ((this._SOPHIEU != value))
				{
					this.OnSOPHIEUChanging(value);
					this.SendPropertyChanging();
					this._SOPHIEU = value;
					this.SendPropertyChanged("SOPHIEU");
					this.OnSOPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYHUY", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYHUY
		{
			get
			{
				return this._NGAYHUY;
			}
			set
			{
				if ((this._NGAYHUY != value))
				{
					this.OnNGAYHUYChanging(value);
					this.SendPropertyChanging();
					this._NGAYHUY = value;
					this.SendPropertyChanged("NGAYHUY");
					this.OnNGAYHUYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEULUCHUY", DbType="NVarChar(255)")]
		public string HIEULUCHUY
		{
			get
			{
				return this._HIEULUCHUY;
			}
			set
			{
				if ((this._HIEULUCHUY != value))
				{
					this.OnHIEULUCHUYChanging(value);
					this.SendPropertyChanging();
					this._HIEULUCHUY = value;
					this.SendPropertyChanged("HIEULUCHUY");
					this.OnHIEULUCHUYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENNHAN", DbType="NVarChar(MAX)")]
		public string NGUYENNHAN
		{
			get
			{
				return this._NGUYENNHAN;
			}
			set
			{
				if ((this._NGUYENNHAN != value))
				{
					this.OnNGUYENNHANChanging(value);
					this.SendPropertyChanging();
					this._NGUYENNHAN = value;
					this.SendPropertyChanged("NGUYENNHAN");
					this.OnNGUYENNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(MAX)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAILAPDB", DbType="Bit")]
		public System.Nullable<bool> TAILAPDB
		{
			get
			{
				return this._TAILAPDB;
			}
			set
			{
				if ((this._TAILAPDB != value))
				{
					this.OnTAILAPDBChanging(value);
					this.SendPropertyChanging();
					this._TAILAPDB = value;
					this.SendPropertyChanged("TAILAPDB");
					this.OnTAILAPDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAILAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTAILAP
		{
			get
			{
				return this._NGAYTAILAP;
			}
			set
			{
				if ((this._NGAYTAILAP != value))
				{
					this.OnNGAYTAILAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAILAP = value;
					this.SendPropertyChanged("NGAYTAILAP");
					this.OnNGAYTAILAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_SOPHIEU", DbType="NVarChar(255)")]
		public string TL_SOPHIEU
		{
			get
			{
				return this._TL_SOPHIEU;
			}
			set
			{
				if ((this._TL_SOPHIEU != value))
				{
					this.OnTL_SOPHIEUChanging(value);
					this.SendPropertyChanging();
					this._TL_SOPHIEU = value;
					this.SendPropertyChanged("TL_SOPHIEU");
					this.OnTL_SOPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_HIEULUC", DbType="NVarChar(255)")]
		public string TL_HIEULUC
		{
			get
			{
				return this._TL_HIEULUC;
			}
			set
			{
				if ((this._TL_HIEULUC != value))
				{
					this.OnTL_HIEULUCChanging(value);
					this.SendPropertyChanging();
					this._TL_HIEULUC = value;
					this.SendPropertyChanged("TL_HIEULUC");
					this.OnTL_HIEULUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_DOT", DbType="NVarChar(255)")]
		public string TL_DOT
		{
			get
			{
				return this._TL_DOT;
			}
			set
			{
				if ((this._TL_DOT != value))
				{
					this.OnTL_DOTChanging(value);
					this.SendPropertyChanging();
					this._TL_DOT = value;
					this.SendPropertyChanged("TL_DOT");
					this.OnTL_DOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="NVarChar(100)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFYDATE
		{
			get
			{
				return this._MODIFYDATE;
			}
			set
			{
				if ((this._MODIFYDATE != value))
				{
					this.OnMODIFYDATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFYDATE = value;
					this.SendPropertyChanged("MODIFYDATE");
					this.OnMODIFYDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYBY", DbType="NVarChar(100)")]
		public string MODIFYBY
		{
			get
			{
				return this._MODIFYBY;
			}
			set
			{
				if ((this._MODIFYBY != value))
				{
					this.OnMODIFYBYChanging(value);
					this.SendPropertyChanging();
					this._MODIFYBY = value;
					this.SendPropertyChanged("MODIFYBY");
					this.OnMODIFYBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADMA", DbType="VarChar(255)")]
		public string MADMA
		{
			get
			{
				return this._MADMA;
			}
			set
			{
				if ((this._MADMA != value))
				{
					this.OnMADMAChanging(value);
					this.SendPropertyChanging();
					this._MADMA = value;
					this.SendPropertyChanged("MADMA");
					this.OnMADMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUKYDS", DbType="Int")]
		public System.Nullable<int> CHUKYDS
		{
			get
			{
				return this._CHUKYDS;
			}
			set
			{
				if ((this._CHUKYDS != value))
				{
					this.OnCHUKYDSChanging(value);
					this.SendPropertyChanging();
					this._CHUKYDS = value;
					this.SendPropertyChanged("CHUKYDS");
					this.OnCHUKYDSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_DULIEUKHACHHANG_IMG")]
	public partial class TB_DULIEUKHACHHANG_IMG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _NGAYUP;
		
		private string _DANHBO;
		
		private string _Loai;
		
		private System.Data.Linq.Binary _IMG;
		
		private System.Data.Linq.Binary _Video;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNGAYUPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYUPChanged();
    partial void OnDANHBOChanging(string value);
    partial void OnDANHBOChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnIMGChanging(System.Data.Linq.Binary value);
    partial void OnIMGChanged();
    partial void OnVideoChanging(System.Data.Linq.Binary value);
    partial void OnVideoChanged();
    #endregion
		
		public TB_DULIEUKHACHHANG_IMG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYUP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYUP
		{
			get
			{
				return this._NGAYUP;
			}
			set
			{
				if ((this._NGAYUP != value))
				{
					this.OnNGAYUPChanging(value);
					this.SendPropertyChanging();
					this._NGAYUP = value;
					this.SendPropertyChanged("NGAYUP");
					this.OnNGAYUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANHBO", DbType="NVarChar(50)")]
		public string DANHBO
		{
			get
			{
				return this._DANHBO;
			}
			set
			{
				if ((this._DANHBO != value))
				{
					this.OnDANHBOChanging(value);
					this.SendPropertyChanging();
					this._DANHBO = value;
					this.SendPropertyChanged("DANHBO");
					this.OnDANHBOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(50)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMG", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary IMG
		{
			get
			{
				return this._IMG;
			}
			set
			{
				if ((this._IMG != value))
				{
					this.OnIMGChanging(value);
					this.SendPropertyChanging();
					this._IMG = value;
					this.SendPropertyChanged("IMG");
					this.OnIMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Video", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Video
		{
			get
			{
				return this._Video;
			}
			set
			{
				if ((this._Video != value))
				{
					this.OnVideoChanging(value);
					this.SendPropertyChanging();
					this._Video = value;
					this.SendPropertyChanged("Video");
					this.OnVideoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
