SELECT * FROM DON_KHACHHANG WHERE SHS='13001170'
SELECT * FROM TOTHIETKE WHERE SHS='13001170'

SELECT * FROM TMP_TAIXET WHERE MAHOSO='13001170'

SELECT * FROM BG_KHOILUONGXDCB WHERE SHS='13001170'



UPDATE TOTHIETKE SET TRAHS='False', NGAYTRAHS = NULL,NGAYCHUYENHS= NULL ,BOPHANCHUYEN =NULL,NGAYTKGD=NULL,HOANTATTK='False', NGAYHOANTATTK=NULL 
WHERE SHS='13001170'


UPDATE TOTHIETKE SET  NGAYTRAHS = NULL,NGAYCHUYENHS= NULL ,BOPHANCHUYEN =NULL,HOANTATTK='False', NGAYHOANTATTK=NULL  WHERE SHS='13001047'