#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHCD_KiemPhieu.DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DH_CODONG")]
	public partial class TanHoaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDSCODONG(DSCODONG instance);
    partial void UpdateDSCODONG(DSCODONG instance);
    partial void DeleteDSCODONG(DSCODONG instance);
    partial void InsertKIEMPHIEU(KIEMPHIEU instance);
    partial void UpdateKIEMPHIEU(KIEMPHIEU instance);
    partial void DeleteKIEMPHIEU(KIEMPHIEU instance);
    #endregion
		
		public TanHoaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DH_CODONGConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TanHoaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TanHoaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TanHoaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TanHoaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DSCODONG> DSCODONGs
		{
			get
			{
				return this.GetTable<DSCODONG>();
			}
		}
		
		public System.Data.Linq.Table<SYS_USER> SYS_USERs
		{
			get
			{
				return this.GetTable<SYS_USER>();
			}
		}
		
		public System.Data.Linq.Table<KIEMPHIEU> KIEMPHIEUs
		{
			get
			{
				return this.GetTable<KIEMPHIEU>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BC_TONGKET")]
		public int BC_TONGKET([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TUNGAY", DbType="VarChar(50)")] string tUNGAY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DENNGAY", DbType="VarChar(50)")] string dENNGAY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HIEULUC", DbType="VarChar(50)")] string hIEULUC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tUNGAY, dENNGAY, hIEULUC);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THONGKEDHN_TP")]
		public int THONGKEDHN_TP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KY", DbType="Int")] System.Nullable<int> kY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kY, nAM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THONGKEDHN")]
		public int THONGKEDHN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KY", DbType="Int")] System.Nullable<int> kY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kY, nAM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THONGKEDHN_TB01")]
		public int THONGKEDHN_TB01([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KY", DbType="Int")] System.Nullable<int> kY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kY, nAM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.THONGKEDHN_TB02")]
		public int THONGKEDHN_TB02([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KY", DbType="Int")] System.Nullable<int> kY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAM", DbType="Int")] System.Nullable<int> nAM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kY, nAM);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DSCODONG")]
	public partial class DSCODONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private int _STTCD;
		
		private string _MACD;
		
		private string _TENCD;
		
		private string _CMND;
		
		private System.Nullable<System.DateTime> _NGAYCAP;
		
		private string _NOICAP;
		
		private string _DIACHI;
		
		private System.Nullable<int> _CDGD;
		
		private System.Nullable<int> _PHONGTOA;
		
		private System.Nullable<int> _TONGCD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnSTTCDChanging(int value);
    partial void OnSTTCDChanged();
    partial void OnMACDChanging(string value);
    partial void OnMACDChanged();
    partial void OnTENCDChanging(string value);
    partial void OnTENCDChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnNGAYCAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCAPChanged();
    partial void OnNOICAPChanging(string value);
    partial void OnNOICAPChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnCDGDChanging(System.Nullable<int> value);
    partial void OnCDGDChanged();
    partial void OnPHONGTOAChanging(System.Nullable<int> value);
    partial void OnPHONGTOAChanged();
    partial void OnTONGCDChanging(System.Nullable<int> value);
    partial void OnTONGCDChanged();
    #endregion
		
		public DSCODONG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL")]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTCD", DbType="Int NOT NULL")]
		public int STTCD
		{
			get
			{
				return this._STTCD;
			}
			set
			{
				if ((this._STTCD != value))
				{
					this.OnSTTCDChanging(value);
					this.SendPropertyChanging();
					this._STTCD = value;
					this.SendPropertyChanged("STTCD");
					this.OnSTTCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCD", DbType="NVarChar(MAX)")]
		public string TENCD
		{
			get
			{
				return this._TENCD;
			}
			set
			{
				if ((this._TENCD != value))
				{
					this.OnTENCDChanging(value);
					this.SendPropertyChanging();
					this._TENCD = value;
					this.SendPropertyChanged("TENCD");
					this.OnTENCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(MAX)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYCAP
		{
			get
			{
				return this._NGAYCAP;
			}
			set
			{
				if ((this._NGAYCAP != value))
				{
					this.OnNGAYCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAP = value;
					this.SendPropertyChanged("NGAYCAP");
					this.OnNGAYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOICAP", DbType="NVarChar(MAX)")]
		public string NOICAP
		{
			get
			{
				return this._NOICAP;
			}
			set
			{
				if ((this._NOICAP != value))
				{
					this.OnNOICAPChanging(value);
					this.SendPropertyChanging();
					this._NOICAP = value;
					this.SendPropertyChanged("NOICAP");
					this.OnNOICAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(MAX)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDGD", DbType="Int")]
		public System.Nullable<int> CDGD
		{
			get
			{
				return this._CDGD;
			}
			set
			{
				if ((this._CDGD != value))
				{
					this.OnCDGDChanging(value);
					this.SendPropertyChanging();
					this._CDGD = value;
					this.SendPropertyChanged("CDGD");
					this.OnCDGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONGTOA", DbType="Int")]
		public System.Nullable<int> PHONGTOA
		{
			get
			{
				return this._PHONGTOA;
			}
			set
			{
				if ((this._PHONGTOA != value))
				{
					this.OnPHONGTOAChanging(value);
					this.SendPropertyChanging();
					this._PHONGTOA = value;
					this.SendPropertyChanged("PHONGTOA");
					this.OnPHONGTOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGCD", DbType="Int")]
		public System.Nullable<int> TONGCD
		{
			get
			{
				return this._TONGCD;
			}
			set
			{
				if ((this._TONGCD != value))
				{
					this.OnTONGCDChanging(value);
					this.SendPropertyChanging();
					this._TONGCD = value;
					this.SendPropertyChanged("TONGCD");
					this.OnTONGCDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYS_USERS")]
	public partial class SYS_USER
	{
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		public SYS_USER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KIEMPHIEU")]
	public partial class KIEMPHIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _LANBQ;
		
		private System.Nullable<System.DateTime> _NGAYBQ;
		
		private System.Nullable<bool> _LOAIBQ;
		
		private int _STTCD;
		
		private string _MACD;
		
		private System.Nullable<int> _TONGCD;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLANBQChanging(int value);
    partial void OnLANBQChanged();
    partial void OnNGAYBQChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYBQChanged();
    partial void OnLOAIBQChanging(System.Nullable<bool> value);
    partial void OnLOAIBQChanged();
    partial void OnSTTCDChanging(int value);
    partial void OnSTTCDChanged();
    partial void OnMACDChanging(string value);
    partial void OnMACDChanged();
    partial void OnTONGCDChanging(System.Nullable<int> value);
    partial void OnTONGCDChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    #endregion
		
		public KIEMPHIEU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANBQ", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LANBQ
		{
			get
			{
				return this._LANBQ;
			}
			set
			{
				if ((this._LANBQ != value))
				{
					this.OnLANBQChanging(value);
					this.SendPropertyChanging();
					this._LANBQ = value;
					this.SendPropertyChanged("LANBQ");
					this.OnLANBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYBQ
		{
			get
			{
				return this._NGAYBQ;
			}
			set
			{
				if ((this._NGAYBQ != value))
				{
					this.OnNGAYBQChanging(value);
					this.SendPropertyChanging();
					this._NGAYBQ = value;
					this.SendPropertyChanged("NGAYBQ");
					this.OnNGAYBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIBQ", DbType="Bit")]
		public System.Nullable<bool> LOAIBQ
		{
			get
			{
				return this._LOAIBQ;
			}
			set
			{
				if ((this._LOAIBQ != value))
				{
					this.OnLOAIBQChanging(value);
					this.SendPropertyChanging();
					this._LOAIBQ = value;
					this.SendPropertyChanged("LOAIBQ");
					this.OnLOAIBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTCD", DbType="Int NOT NULL")]
		public int STTCD
		{
			get
			{
				return this._STTCD;
			}
			set
			{
				if ((this._STTCD != value))
				{
					this.OnSTTCDChanging(value);
					this.SendPropertyChanging();
					this._STTCD = value;
					this.SendPropertyChanged("STTCD");
					this.OnSTTCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGCD", DbType="Int")]
		public System.Nullable<int> TONGCD
		{
			get
			{
				return this._TONGCD;
			}
			set
			{
				if ((this._TONGCD != value))
				{
					this.OnTONGCDChanging(value);
					this.SendPropertyChanging();
					this._TONGCD = value;
					this.SendPropertyChanged("TONGCD");
					this.OnTONGCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="VarChar(20)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
