<?xml version="1.0" encoding="utf-8"?><Database Name="DH_CODONG" Class="TanHoaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HP_G7\KD;Initial Catalog=DH_CODONG;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DH_CODONGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DSCODONG" Member="DSCODONGs">
    <Type Name="DSCODONG">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STTCD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MACD" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NGAYCAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NOICAP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CDGD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PHONGTOA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_USERS" Member="SYS_USERs">
    <Type Name="SYS_USER">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KIEMPHIEU" Member="KIEMPHIEUs">
    <Type Name="KIEMPHIEU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LANBQ" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYBQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LOAIBQ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="STTCD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MACD" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TONGCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.BC_TONGKET" Method="BC_TONGKET">
    <Parameter Name="TUNGAY" Parameter="tUNGAY" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DENNGAY" Parameter="dENNGAY" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="HIEULUC" Parameter="hIEULUC" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THONGKEDHN_TP" Method="THONGKEDHN_TP">
    <Parameter Name="KY" Parameter="kY" Type="System.Int32" DbType="Int" />
    <Parameter Name="NAM" Parameter="nAM" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THONGKEDHN" Method="THONGKEDHN">
    <Parameter Name="KY" Parameter="kY" Type="System.Int32" DbType="Int" />
    <Parameter Name="NAM" Parameter="nAM" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THONGKEDHN_TB01" Method="THONGKEDHN_TB01">
    <Parameter Name="KY" Parameter="kY" Type="System.Int32" DbType="Int" />
    <Parameter Name="NAM" Parameter="nAM" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THONGKEDHN_TB02" Method="THONGKEDHN_TB02">
    <Parameter Name="KY" Parameter="kY" Type="System.Int32" DbType="Int" />
    <Parameter Name="NAM" Parameter="nAM" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>