USE MASTER
GO

IF EXISTS( SELECT * FROM  sys.databases WHERE NAME = 'DH_CODONG')
   DROP DATABASE DH_CODONG
USE MASTER
GO
CREATE DATABASE DH_CODONG
GO	

USE DH_CODONG
GO

CREATE TABLE [dbo].[SYS_USERS](
	[USERNAME] [varchar](20) NOT NULL,
	[PASSWORD] [varchar](50) NULL
)
GO

CREATE TABLE DSCODONG_THAMDU
(
	STT		INT NOT NULL,
	STTCD	INT NOT NULL,
	MACD	VARCHAR(20) PRIMARY KEY NOT NULL,
	TENCD	NVARCHAR(MAX),
	CMND	NVARCHAR(MAX),
	NGAYCAP	DATE,
	NOICAP	NVARCHAR(MAX),
	DIACHI	NVARCHAR(MAX),
	CDGD	INT,
	PHONGTOA	INT,
	TONGCD	INT
)
GO

CREATE TABLE DSCODONG
(
	STT		INT NOT NULL,
	STTCD	INT NOT NULL,
	MACD	VARCHAR(20) PRIMARY KEY NOT NULL,
	TENCD	NVARCHAR(MAX),
	CMND	NVARCHAR(MAX),
	NGAYCAP	DATE,
	NOICAP	NVARCHAR(MAX),
	DIACHI	NVARCHAR(MAX),
	CDGD	INT,
	PHONGTOA	INT,
	TONGCD	INT
)
GO

CREATE TABLE KIEMPHIEU
(
	ID INT IDENTITY(1,1),
	LANBQ INT,
	NGAYBQ DATETIME,
	LOAIBQ BIT,
	STTCD	INT NOT NULL,
	MACD	VARCHAR(20) NOT NULL,
	TONGCD	INT,
	CREATEBY VARCHAR(20),
	CREATEDATE DATETIME,
	CONSTRAINT FK_KIEMPHIEU PRIMARY KEY (LANBQ,MACD,NGAYBQ)
)
GO

CREATE TABLE BIEUQUYET
(
	ID INT IDENTITY(1,1),
	LANBQ INT,
	NGAYBQ DATETIME,
	LOAIBQ BIT,
	STTCD	INT NOT NULL,
	MACD	VARCHAR(20) NOT NULL,
	TONGCD	INT,
	C1		INT,
	C2		INT,
	C3		INT,
	CREATEBY VARCHAR(20),
	CREATEDATE DATETIME,
	CONSTRAINT FK_BIEUQUYET PRIMARY KEY (LANBQ,MACD,NGAYBQ)
)
GO

ALTER  PROC p_BIEUQUYET
	@LAN VARCHAR(50),
	@NGAY VARCHAR(50)
as

DECLARE @SUMCD FLOAT
SELECT @SUMCD= SUM(TONGCD) FROM DSCODONG_THAMDU

SELECT COUNT(CASE WHEN C1=1 THEN 1 ELSE NULL END) AS _1C1,SUM(CASE WHEN C1=1 THEN TONGCD ELSE NULL END) AS _1S1,CONVERT(varchar(50),100.0*ROUND((SUM(CASE WHEN C1=1 THEN TONGCD ELSE NULL END)/@SUMCD),4))+'%' as _1T1,
	   COUNT(CASE WHEN C1=2 THEN 1 ELSE NULL END) AS _1C2,SUM(CASE WHEN C1=2 THEN TONGCD ELSE NULL END) AS _1S2,CONVERT(varchar(50),100.0*ROUND((SUM(CASE WHEN C1=2 THEN TONGCD ELSE NULL END)/@SUMCD),4))+'%' as _1T2,
	   COUNT(CASE WHEN C1=3 THEN 1 ELSE NULL END) AS _1C3,SUM(CASE WHEN C1=3 THEN TONGCD ELSE NULL END) AS _1S3,CONVERT(varchar(50),100.0*ROUND((SUM(CASE WHEN C1=3 THEN TONGCD ELSE NULL END)/@SUMCD),4))+'%' as _1T3,
	   COUNT(CASE WHEN C2=1 THEN 1 ELSE NULL END) AS _2C1,SUM(CASE WHEN C2=1 THEN TONGCD ELSE NULL END) AS _2S1,CONVERT(varchar(50),100.0*ROUND((SUM(CASE WHEN C2=1 THEN TONGCD ELSE NULL END)/@SUMCD),4))+'%' as _2T1,
	   COUNT(CASE WHEN C2=2 THEN 1 ELSE NULL END) AS _2C2,SUM(CASE WHEN C2=2 THEN TONGCD ELSE NULL END) AS _2S2,CONVERT(varchar(50),100.0*ROUND((SUM(CASE WHEN C2=2 THEN TONGCD ELSE NULL END)/@SUMCD),4))+'%' as _2T2,
	   COUNT(CASE WHEN C2=3 THEN 1 ELSE NULL END) AS _2C3,SUM(CASE WHEN C2=3 THEN TONGCD ELSE NULL END) AS _2S3,CONVERT(varchar(50),100.0*ROUND((SUM(CASE WHEN C2=3 THEN TONGCD ELSE NULL END)/@SUMCD),4))+'%' as _2T3,
	   COUNT(CASE WHEN C3=1 THEN 1 ELSE NULL END) AS _3C1,SUM(CASE WHEN C3=1 THEN TONGCD ELSE NULL END) AS _3S1,CONVERT(varchar(50),100.0*ROUND((SUM(CASE WHEN C3=1 THEN TONGCD ELSE NULL END)/@SUMCD),4))+'%' as _3T1,
	   COUNT(CASE WHEN C3=2 THEN 1 ELSE NULL END) AS _3C2,SUM(CASE WHEN C3=2 THEN TONGCD ELSE NULL END) AS _3S2,CONVERT(varchar(50),100.0*ROUND((SUM(CASE WHEN C3=2 THEN TONGCD ELSE NULL END)/@SUMCD),4))+'%' as _3T2,
	   COUNT(CASE WHEN C3=3 THEN 1 ELSE NULL END) AS _3C3,SUM(CASE WHEN C3=3 THEN TONGCD ELSE NULL END) AS _3S3,CONVERT(varchar(50),100.0*ROUND((SUM(CASE WHEN C3=3 THEN TONGCD ELSE NULL END)/@SUMCD),4))+'%' as _3T3
FROM BIEUQUYET
WHERE  LANBQ= @LAN AND CONVERT(VARCHAR(50),NGAYBQ,103)=@NGAY


CREATE TABLE BAUCU
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	LANBC INT,
	NGAYBC DATETIME,
	STT	INT,
	TENBC	NVARCHAR(50),
	SLDY	INT,
	SLKDY	INT,
	CREATEBY VARCHAR(20),
	CREATEDATE DATETIME
)


