#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BauCu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DH_CODONG")]
	public partial class dbDH_CODONGDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBAUCU(BAUCU instance);
    partial void UpdateBAUCU(BAUCU instance);
    partial void DeleteBAUCU(BAUCU instance);
    partial void InsertBIEUQUYET(BIEUQUYET instance);
    partial void UpdateBIEUQUYET(BIEUQUYET instance);
    partial void DeleteBIEUQUYET(BIEUQUYET instance);
    partial void InsertDSCODONG(DSCODONG instance);
    partial void UpdateDSCODONG(DSCODONG instance);
    partial void DeleteDSCODONG(DSCODONG instance);
    partial void InsertDSCODONG_THAMDU(DSCODONG_THAMDU instance);
    partial void UpdateDSCODONG_THAMDU(DSCODONG_THAMDU instance);
    partial void DeleteDSCODONG_THAMDU(DSCODONG_THAMDU instance);
    partial void InsertKHONGHOPLE(KHONGHOPLE instance);
    partial void UpdateKHONGHOPLE(KHONGHOPLE instance);
    partial void DeleteKHONGHOPLE(KHONGHOPLE instance);
    partial void InsertKIEMPHIEU_BAUCU(KIEMPHIEU_BAUCU instance);
    partial void UpdateKIEMPHIEU_BAUCU(KIEMPHIEU_BAUCU instance);
    partial void DeleteKIEMPHIEU_BAUCU(KIEMPHIEU_BAUCU instance);
    partial void InsertKIEMPHIEU_BIEUQUYET(KIEMPHIEU_BIEUQUYET instance);
    partial void UpdateKIEMPHIEU_BIEUQUYET(KIEMPHIEU_BIEUQUYET instance);
    partial void DeleteKIEMPHIEU_BIEUQUYET(KIEMPHIEU_BIEUQUYET instance);
    partial void InsertUNGVIEN(UNGVIEN instance);
    partial void UpdateUNGVIEN(UNGVIEN instance);
    partial void DeleteUNGVIEN(UNGVIEN instance);
    #endregion
		
		public dbDH_CODONGDataContext() : 
				base(global::BauCu.Properties.Settings.Default.DH_CODONGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDH_CODONGDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDH_CODONGDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDH_CODONGDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDH_CODONGDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BAUCU> BAUCUs
		{
			get
			{
				return this.GetTable<BAUCU>();
			}
		}
		
		public System.Data.Linq.Table<TIEUCHIBIEUQUYET> TIEUCHIBIEUQUYETs
		{
			get
			{
				return this.GetTable<TIEUCHIBIEUQUYET>();
			}
		}
		
		public System.Data.Linq.Table<BIEUQUYET> BIEUQUYETs
		{
			get
			{
				return this.GetTable<BIEUQUYET>();
			}
		}
		
		public System.Data.Linq.Table<DSCODONG> DSCODONGs
		{
			get
			{
				return this.GetTable<DSCODONG>();
			}
		}
		
		public System.Data.Linq.Table<DSCODONG_THAMDU> DSCODONG_THAMDUs
		{
			get
			{
				return this.GetTable<DSCODONG_THAMDU>();
			}
		}
		
		public System.Data.Linq.Table<KHONGHOPLE> KHONGHOPLEs
		{
			get
			{
				return this.GetTable<KHONGHOPLE>();
			}
		}
		
		public System.Data.Linq.Table<KIEMPHIEU_BAUCU> KIEMPHIEU_BAUCUs
		{
			get
			{
				return this.GetTable<KIEMPHIEU_BAUCU>();
			}
		}
		
		public System.Data.Linq.Table<KIEMPHIEU_BIEUQUYET> KIEMPHIEU_BIEUQUYETs
		{
			get
			{
				return this.GetTable<KIEMPHIEU_BIEUQUYET>();
			}
		}
		
		public System.Data.Linq.Table<SYS_USER> SYS_USERs
		{
			get
			{
				return this.GetTable<SYS_USER>();
			}
		}
		
		public System.Data.Linq.Table<UNGVIEN> UNGVIENs
		{
			get
			{
				return this.GetTable<UNGVIEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAUCU")]
	public partial class BAUCU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _LANBC;
		
		private System.Nullable<System.DateTime> _NGAYBC;
		
		private System.Nullable<int> _STT;
		
		private string _TENBC;
		
		private System.Nullable<int> _SLDY;
		
		private System.Nullable<int> _SLKDY;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLANBCChanging(System.Nullable<int> value);
    partial void OnLANBCChanged();
    partial void OnNGAYBCChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYBCChanged();
    partial void OnSTTChanging(System.Nullable<int> value);
    partial void OnSTTChanged();
    partial void OnTENBCChanging(string value);
    partial void OnTENBCChanged();
    partial void OnSLDYChanging(System.Nullable<int> value);
    partial void OnSLDYChanged();
    partial void OnSLKDYChanging(System.Nullable<int> value);
    partial void OnSLKDYChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    #endregion
		
		public BAUCU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANBC", DbType="Int")]
		public System.Nullable<int> LANBC
		{
			get
			{
				return this._LANBC;
			}
			set
			{
				if ((this._LANBC != value))
				{
					this.OnLANBCChanging(value);
					this.SendPropertyChanging();
					this._LANBC = value;
					this.SendPropertyChanged("LANBC");
					this.OnLANBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBC", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYBC
		{
			get
			{
				return this._NGAYBC;
			}
			set
			{
				if ((this._NGAYBC != value))
				{
					this.OnNGAYBCChanging(value);
					this.SendPropertyChanging();
					this._NGAYBC = value;
					this.SendPropertyChanged("NGAYBC");
					this.OnNGAYBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBC", DbType="NVarChar(50)")]
		public string TENBC
		{
			get
			{
				return this._TENBC;
			}
			set
			{
				if ((this._TENBC != value))
				{
					this.OnTENBCChanging(value);
					this.SendPropertyChanging();
					this._TENBC = value;
					this.SendPropertyChanged("TENBC");
					this.OnTENBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLDY", DbType="Int")]
		public System.Nullable<int> SLDY
		{
			get
			{
				return this._SLDY;
			}
			set
			{
				if ((this._SLDY != value))
				{
					this.OnSLDYChanging(value);
					this.SendPropertyChanging();
					this._SLDY = value;
					this.SendPropertyChanged("SLDY");
					this.OnSLDYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLKDY", DbType="Int")]
		public System.Nullable<int> SLKDY
		{
			get
			{
				return this._SLKDY;
			}
			set
			{
				if ((this._SLKDY != value))
				{
					this.OnSLKDYChanging(value);
					this.SendPropertyChanging();
					this._SLKDY = value;
					this.SendPropertyChanged("SLKDY");
					this.OnSLKDYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="VarChar(20)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIEUCHIBIEUQUYET")]
	public partial class TIEUCHIBIEUQUYET
	{
		
		private System.Nullable<int> _STT;
		
		private string _TENLOAI;
		
		public TIEUCHIBIEUQUYET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(MAX)")]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this._TENLOAI = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BIEUQUYET")]
	public partial class BIEUQUYET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _LANBQ;
		
		private System.DateTime _NGAYBQ;
		
		private System.Nullable<bool> _LOAIBQ;
		
		private int _STTCD;
		
		private string _MACD;
		
		private System.Nullable<int> _TONGCD;
		
		private System.Nullable<int> _C1;
		
		private System.Nullable<int> _C2;
		
		private System.Nullable<int> _C3;
		
		private System.Nullable<int> _C4;
		
		private System.Nullable<int> _C5;
		
		private System.Nullable<int> _C6;
		
		private System.Nullable<int> _C7;
		
		private System.Nullable<int> _C8;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLANBQChanging(int value);
    partial void OnLANBQChanged();
    partial void OnNGAYBQChanging(System.DateTime value);
    partial void OnNGAYBQChanged();
    partial void OnLOAIBQChanging(System.Nullable<bool> value);
    partial void OnLOAIBQChanged();
    partial void OnSTTCDChanging(int value);
    partial void OnSTTCDChanged();
    partial void OnMACDChanging(string value);
    partial void OnMACDChanged();
    partial void OnTONGCDChanging(System.Nullable<int> value);
    partial void OnTONGCDChanged();
    partial void OnC1Changing(System.Nullable<int> value);
    partial void OnC1Changed();
    partial void OnC2Changing(System.Nullable<int> value);
    partial void OnC2Changed();
    partial void OnC3Changing(System.Nullable<int> value);
    partial void OnC3Changed();
    partial void OnC4Changing(System.Nullable<int> value);
    partial void OnC4Changed();
    partial void OnC5Changing(System.Nullable<int> value);
    partial void OnC5Changed();
    partial void OnC6Changing(System.Nullable<int> value);
    partial void OnC6Changed();
    partial void OnC7Changing(System.Nullable<int> value);
    partial void OnC7Changed();
    partial void OnC8Changing(System.Nullable<int> value);
    partial void OnC8Changed();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    #endregion
		
		public BIEUQUYET()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANBQ", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LANBQ
		{
			get
			{
				return this._LANBQ;
			}
			set
			{
				if ((this._LANBQ != value))
				{
					this.OnLANBQChanging(value);
					this.SendPropertyChanging();
					this._LANBQ = value;
					this.SendPropertyChanged("LANBQ");
					this.OnLANBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBQ", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NGAYBQ
		{
			get
			{
				return this._NGAYBQ;
			}
			set
			{
				if ((this._NGAYBQ != value))
				{
					this.OnNGAYBQChanging(value);
					this.SendPropertyChanging();
					this._NGAYBQ = value;
					this.SendPropertyChanged("NGAYBQ");
					this.OnNGAYBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIBQ", DbType="Bit")]
		public System.Nullable<bool> LOAIBQ
		{
			get
			{
				return this._LOAIBQ;
			}
			set
			{
				if ((this._LOAIBQ != value))
				{
					this.OnLOAIBQChanging(value);
					this.SendPropertyChanging();
					this._LOAIBQ = value;
					this.SendPropertyChanged("LOAIBQ");
					this.OnLOAIBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTCD", DbType="Int NOT NULL")]
		public int STTCD
		{
			get
			{
				return this._STTCD;
			}
			set
			{
				if ((this._STTCD != value))
				{
					this.OnSTTCDChanging(value);
					this.SendPropertyChanging();
					this._STTCD = value;
					this.SendPropertyChanged("STTCD");
					this.OnSTTCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGCD", DbType="Int")]
		public System.Nullable<int> TONGCD
		{
			get
			{
				return this._TONGCD;
			}
			set
			{
				if ((this._TONGCD != value))
				{
					this.OnTONGCDChanging(value);
					this.SendPropertyChanging();
					this._TONGCD = value;
					this.SendPropertyChanged("TONGCD");
					this.OnTONGCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C1", DbType="Int")]
		public System.Nullable<int> C1
		{
			get
			{
				return this._C1;
			}
			set
			{
				if ((this._C1 != value))
				{
					this.OnC1Changing(value);
					this.SendPropertyChanging();
					this._C1 = value;
					this.SendPropertyChanged("C1");
					this.OnC1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C2", DbType="Int")]
		public System.Nullable<int> C2
		{
			get
			{
				return this._C2;
			}
			set
			{
				if ((this._C2 != value))
				{
					this.OnC2Changing(value);
					this.SendPropertyChanging();
					this._C2 = value;
					this.SendPropertyChanged("C2");
					this.OnC2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C3", DbType="Int")]
		public System.Nullable<int> C3
		{
			get
			{
				return this._C3;
			}
			set
			{
				if ((this._C3 != value))
				{
					this.OnC3Changing(value);
					this.SendPropertyChanging();
					this._C3 = value;
					this.SendPropertyChanged("C3");
					this.OnC3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C4", DbType="Int")]
		public System.Nullable<int> C4
		{
			get
			{
				return this._C4;
			}
			set
			{
				if ((this._C4 != value))
				{
					this.OnC4Changing(value);
					this.SendPropertyChanging();
					this._C4 = value;
					this.SendPropertyChanged("C4");
					this.OnC4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C5", DbType="Int")]
		public System.Nullable<int> C5
		{
			get
			{
				return this._C5;
			}
			set
			{
				if ((this._C5 != value))
				{
					this.OnC5Changing(value);
					this.SendPropertyChanging();
					this._C5 = value;
					this.SendPropertyChanged("C5");
					this.OnC5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C6", DbType="Int")]
		public System.Nullable<int> C6
		{
			get
			{
				return this._C6;
			}
			set
			{
				if ((this._C6 != value))
				{
					this.OnC6Changing(value);
					this.SendPropertyChanging();
					this._C6 = value;
					this.SendPropertyChanged("C6");
					this.OnC6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C7", DbType="Int")]
		public System.Nullable<int> C7
		{
			get
			{
				return this._C7;
			}
			set
			{
				if ((this._C7 != value))
				{
					this.OnC7Changing(value);
					this.SendPropertyChanging();
					this._C7 = value;
					this.SendPropertyChanged("C7");
					this.OnC7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C8", DbType="Int")]
		public System.Nullable<int> C8
		{
			get
			{
				return this._C8;
			}
			set
			{
				if ((this._C8 != value))
				{
					this.OnC8Changing(value);
					this.SendPropertyChanging();
					this._C8 = value;
					this.SendPropertyChanged("C8");
					this.OnC8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="VarChar(20)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DSCODONG")]
	public partial class DSCODONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private int _STTCD;
		
		private string _MACD;
		
		private string _TENCD;
		
		private string _CMND;
		
		private System.Nullable<System.DateTime> _NGAYCAP;
		
		private string _NOICAP;
		
		private string _DIACHI;
		
		private System.Nullable<int> _CDGD;
		
		private System.Nullable<int> _PHONGTOA;
		
		private System.Nullable<int> _TONGCD;
		
		private string _ImgPath;
		
		private System.Data.Linq.Binary _Image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnSTTCDChanging(int value);
    partial void OnSTTCDChanged();
    partial void OnMACDChanging(string value);
    partial void OnMACDChanged();
    partial void OnTENCDChanging(string value);
    partial void OnTENCDChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnNGAYCAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCAPChanged();
    partial void OnNOICAPChanging(string value);
    partial void OnNOICAPChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnCDGDChanging(System.Nullable<int> value);
    partial void OnCDGDChanged();
    partial void OnPHONGTOAChanging(System.Nullable<int> value);
    partial void OnPHONGTOAChanged();
    partial void OnTONGCDChanging(System.Nullable<int> value);
    partial void OnTONGCDChanged();
    partial void OnImgPathChanging(string value);
    partial void OnImgPathChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    #endregion
		
		public DSCODONG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL")]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTCD", DbType="Int NOT NULL")]
		public int STTCD
		{
			get
			{
				return this._STTCD;
			}
			set
			{
				if ((this._STTCD != value))
				{
					this.OnSTTCDChanging(value);
					this.SendPropertyChanging();
					this._STTCD = value;
					this.SendPropertyChanged("STTCD");
					this.OnSTTCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCD", DbType="NVarChar(MAX)")]
		public string TENCD
		{
			get
			{
				return this._TENCD;
			}
			set
			{
				if ((this._TENCD != value))
				{
					this.OnTENCDChanging(value);
					this.SendPropertyChanging();
					this._TENCD = value;
					this.SendPropertyChanged("TENCD");
					this.OnTENCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(MAX)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYCAP
		{
			get
			{
				return this._NGAYCAP;
			}
			set
			{
				if ((this._NGAYCAP != value))
				{
					this.OnNGAYCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAP = value;
					this.SendPropertyChanged("NGAYCAP");
					this.OnNGAYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOICAP", DbType="NVarChar(MAX)")]
		public string NOICAP
		{
			get
			{
				return this._NOICAP;
			}
			set
			{
				if ((this._NOICAP != value))
				{
					this.OnNOICAPChanging(value);
					this.SendPropertyChanging();
					this._NOICAP = value;
					this.SendPropertyChanged("NOICAP");
					this.OnNOICAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(MAX)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDGD", DbType="Int")]
		public System.Nullable<int> CDGD
		{
			get
			{
				return this._CDGD;
			}
			set
			{
				if ((this._CDGD != value))
				{
					this.OnCDGDChanging(value);
					this.SendPropertyChanging();
					this._CDGD = value;
					this.SendPropertyChanged("CDGD");
					this.OnCDGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONGTOA", DbType="Int")]
		public System.Nullable<int> PHONGTOA
		{
			get
			{
				return this._PHONGTOA;
			}
			set
			{
				if ((this._PHONGTOA != value))
				{
					this.OnPHONGTOAChanging(value);
					this.SendPropertyChanging();
					this._PHONGTOA = value;
					this.SendPropertyChanged("PHONGTOA");
					this.OnPHONGTOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGCD", DbType="Int")]
		public System.Nullable<int> TONGCD
		{
			get
			{
				return this._TONGCD;
			}
			set
			{
				if ((this._TONGCD != value))
				{
					this.OnTONGCDChanging(value);
					this.SendPropertyChanging();
					this._TONGCD = value;
					this.SendPropertyChanged("TONGCD");
					this.OnTONGCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgPath", DbType="NVarChar(50)")]
		public string ImgPath
		{
			get
			{
				return this._ImgPath;
			}
			set
			{
				if ((this._ImgPath != value))
				{
					this.OnImgPathChanging(value);
					this.SendPropertyChanging();
					this._ImgPath = value;
					this.SendPropertyChanged("ImgPath");
					this.OnImgPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DSCODONG_THAMDU")]
	public partial class DSCODONG_THAMDU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private int _STTCD;
		
		private string _MACD;
		
		private string _TENCD;
		
		private string _CMND;
		
		private System.Nullable<System.DateTime> _NGAYCAP;
		
		private string _NOICAP;
		
		private string _DIACHI;
		
		private System.Nullable<int> _CDGD;
		
		private System.Nullable<int> _PHONGTOA;
		
		private System.Nullable<int> _TONGCD;
		
		private System.Nullable<System.DateTime> _NGAYVAO;
		
		private EntitySet<KIEMPHIEU_BAUCU> _KIEMPHIEU_BAUCUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnSTTCDChanging(int value);
    partial void OnSTTCDChanged();
    partial void OnMACDChanging(string value);
    partial void OnMACDChanged();
    partial void OnTENCDChanging(string value);
    partial void OnTENCDChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnNGAYCAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCAPChanged();
    partial void OnNOICAPChanging(string value);
    partial void OnNOICAPChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnCDGDChanging(System.Nullable<int> value);
    partial void OnCDGDChanged();
    partial void OnPHONGTOAChanging(System.Nullable<int> value);
    partial void OnPHONGTOAChanged();
    partial void OnTONGCDChanging(System.Nullable<int> value);
    partial void OnTONGCDChanged();
    partial void OnNGAYVAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYVAOChanged();
    #endregion
		
		public DSCODONG_THAMDU()
		{
			this._KIEMPHIEU_BAUCUs = new EntitySet<KIEMPHIEU_BAUCU>(new Action<KIEMPHIEU_BAUCU>(this.attach_KIEMPHIEU_BAUCUs), new Action<KIEMPHIEU_BAUCU>(this.detach_KIEMPHIEU_BAUCUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL")]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTCD", DbType="Int NOT NULL")]
		public int STTCD
		{
			get
			{
				return this._STTCD;
			}
			set
			{
				if ((this._STTCD != value))
				{
					this.OnSTTCDChanging(value);
					this.SendPropertyChanging();
					this._STTCD = value;
					this.SendPropertyChanged("STTCD");
					this.OnSTTCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCD", DbType="NVarChar(MAX)")]
		public string TENCD
		{
			get
			{
				return this._TENCD;
			}
			set
			{
				if ((this._TENCD != value))
				{
					this.OnTENCDChanging(value);
					this.SendPropertyChanging();
					this._TENCD = value;
					this.SendPropertyChanged("TENCD");
					this.OnTENCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(MAX)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYCAP
		{
			get
			{
				return this._NGAYCAP;
			}
			set
			{
				if ((this._NGAYCAP != value))
				{
					this.OnNGAYCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAP = value;
					this.SendPropertyChanged("NGAYCAP");
					this.OnNGAYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOICAP", DbType="NVarChar(MAX)")]
		public string NOICAP
		{
			get
			{
				return this._NOICAP;
			}
			set
			{
				if ((this._NOICAP != value))
				{
					this.OnNOICAPChanging(value);
					this.SendPropertyChanging();
					this._NOICAP = value;
					this.SendPropertyChanged("NOICAP");
					this.OnNOICAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(MAX)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDGD", DbType="Int")]
		public System.Nullable<int> CDGD
		{
			get
			{
				return this._CDGD;
			}
			set
			{
				if ((this._CDGD != value))
				{
					this.OnCDGDChanging(value);
					this.SendPropertyChanging();
					this._CDGD = value;
					this.SendPropertyChanged("CDGD");
					this.OnCDGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONGTOA", DbType="Int")]
		public System.Nullable<int> PHONGTOA
		{
			get
			{
				return this._PHONGTOA;
			}
			set
			{
				if ((this._PHONGTOA != value))
				{
					this.OnPHONGTOAChanging(value);
					this.SendPropertyChanging();
					this._PHONGTOA = value;
					this.SendPropertyChanged("PHONGTOA");
					this.OnPHONGTOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGCD", DbType="Int")]
		public System.Nullable<int> TONGCD
		{
			get
			{
				return this._TONGCD;
			}
			set
			{
				if ((this._TONGCD != value))
				{
					this.OnTONGCDChanging(value);
					this.SendPropertyChanging();
					this._TONGCD = value;
					this.SendPropertyChanged("TONGCD");
					this.OnTONGCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYVAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYVAO
		{
			get
			{
				return this._NGAYVAO;
			}
			set
			{
				if ((this._NGAYVAO != value))
				{
					this.OnNGAYVAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYVAO = value;
					this.SendPropertyChanged("NGAYVAO");
					this.OnNGAYVAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DSCODONG_THAMDU_KIEMPHIEU_BAUCU", Storage="_KIEMPHIEU_BAUCUs", ThisKey="MACD", OtherKey="MACD")]
		public EntitySet<KIEMPHIEU_BAUCU> KIEMPHIEU_BAUCUs
		{
			get
			{
				return this._KIEMPHIEU_BAUCUs;
			}
			set
			{
				this._KIEMPHIEU_BAUCUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KIEMPHIEU_BAUCUs(KIEMPHIEU_BAUCU entity)
		{
			this.SendPropertyChanging();
			entity.DSCODONG_THAMDU = this;
		}
		
		private void detach_KIEMPHIEU_BAUCUs(KIEMPHIEU_BAUCU entity)
		{
			this.SendPropertyChanging();
			entity.DSCODONG_THAMDU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHONGHOPLE")]
	public partial class KHONGHOPLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STTCD;
		
		private string _MACD;
		
		private string _TenCD;
		
		private System.Nullable<int> _TONGCD;
		
		private int _LoaiBC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTCDChanging(int value);
    partial void OnSTTCDChanged();
    partial void OnMACDChanging(string value);
    partial void OnMACDChanged();
    partial void OnTenCDChanging(string value);
    partial void OnTenCDChanged();
    partial void OnTONGCDChanging(System.Nullable<int> value);
    partial void OnTONGCDChanged();
    partial void OnLoaiBCChanging(int value);
    partial void OnLoaiBCChanged();
    #endregion
		
		public KHONGHOPLE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTCD", DbType="Int NOT NULL")]
		public int STTCD
		{
			get
			{
				return this._STTCD;
			}
			set
			{
				if ((this._STTCD != value))
				{
					this.OnSTTCDChanging(value);
					this.SendPropertyChanging();
					this._STTCD = value;
					this.SendPropertyChanged("STTCD");
					this.OnSTTCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCD", DbType="NVarChar(MAX)")]
		public string TenCD
		{
			get
			{
				return this._TenCD;
			}
			set
			{
				if ((this._TenCD != value))
				{
					this.OnTenCDChanging(value);
					this.SendPropertyChanging();
					this._TenCD = value;
					this.SendPropertyChanged("TenCD");
					this.OnTenCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGCD", DbType="Int")]
		public System.Nullable<int> TONGCD
		{
			get
			{
				return this._TONGCD;
			}
			set
			{
				if ((this._TONGCD != value))
				{
					this.OnTONGCDChanging(value);
					this.SendPropertyChanging();
					this._TONGCD = value;
					this.SendPropertyChanged("TONGCD");
					this.OnTONGCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBC", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LoaiBC
		{
			get
			{
				return this._LoaiBC;
			}
			set
			{
				if ((this._LoaiBC != value))
				{
					this.OnLoaiBCChanging(value);
					this.SendPropertyChanging();
					this._LoaiBC = value;
					this.SendPropertyChanged("LoaiBC");
					this.OnLoaiBCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KIEMPHIEU_BAUCU")]
	public partial class KIEMPHIEU_BAUCU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _LANBQ;
		
		private System.DateTime _NGAYBQ;
		
		private int _STTCD;
		
		private string _MACD;
		
		private System.Nullable<int> _TONGCD;
		
		private System.Nullable<int> _ID_UngCu;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private EntityRef<DSCODONG_THAMDU> _DSCODONG_THAMDU;
		
		private EntityRef<UNGVIEN> _UNGVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLANBQChanging(int value);
    partial void OnLANBQChanged();
    partial void OnNGAYBQChanging(System.DateTime value);
    partial void OnNGAYBQChanged();
    partial void OnSTTCDChanging(int value);
    partial void OnSTTCDChanged();
    partial void OnMACDChanging(string value);
    partial void OnMACDChanged();
    partial void OnTONGCDChanging(System.Nullable<int> value);
    partial void OnTONGCDChanged();
    partial void OnID_UngCuChanging(System.Nullable<int> value);
    partial void OnID_UngCuChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    #endregion
		
		public KIEMPHIEU_BAUCU()
		{
			this._DSCODONG_THAMDU = default(EntityRef<DSCODONG_THAMDU>);
			this._UNGVIEN = default(EntityRef<UNGVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANBQ", DbType="Int NOT NULL")]
		public int LANBQ
		{
			get
			{
				return this._LANBQ;
			}
			set
			{
				if ((this._LANBQ != value))
				{
					this.OnLANBQChanging(value);
					this.SendPropertyChanging();
					this._LANBQ = value;
					this.SendPropertyChanged("LANBQ");
					this.OnLANBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBQ", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYBQ
		{
			get
			{
				return this._NGAYBQ;
			}
			set
			{
				if ((this._NGAYBQ != value))
				{
					this.OnNGAYBQChanging(value);
					this.SendPropertyChanging();
					this._NGAYBQ = value;
					this.SendPropertyChanged("NGAYBQ");
					this.OnNGAYBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTCD", DbType="Int NOT NULL")]
		public int STTCD
		{
			get
			{
				return this._STTCD;
			}
			set
			{
				if ((this._STTCD != value))
				{
					this.OnSTTCDChanging(value);
					this.SendPropertyChanging();
					this._STTCD = value;
					this.SendPropertyChanged("STTCD");
					this.OnSTTCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					if (this._DSCODONG_THAMDU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGCD", DbType="Int")]
		public System.Nullable<int> TONGCD
		{
			get
			{
				return this._TONGCD;
			}
			set
			{
				if ((this._TONGCD != value))
				{
					this.OnTONGCDChanging(value);
					this.SendPropertyChanging();
					this._TONGCD = value;
					this.SendPropertyChanged("TONGCD");
					this.OnTONGCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_UngCu", DbType="Int")]
		public System.Nullable<int> ID_UngCu
		{
			get
			{
				return this._ID_UngCu;
			}
			set
			{
				if ((this._ID_UngCu != value))
				{
					if (this._UNGVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_UngCuChanging(value);
					this.SendPropertyChanging();
					this._ID_UngCu = value;
					this.SendPropertyChanged("ID_UngCu");
					this.OnID_UngCuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="VarChar(20)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DSCODONG_THAMDU_KIEMPHIEU_BAUCU", Storage="_DSCODONG_THAMDU", ThisKey="MACD", OtherKey="MACD", IsForeignKey=true)]
		public DSCODONG_THAMDU DSCODONG_THAMDU
		{
			get
			{
				return this._DSCODONG_THAMDU.Entity;
			}
			set
			{
				DSCODONG_THAMDU previousValue = this._DSCODONG_THAMDU.Entity;
				if (((previousValue != value) 
							|| (this._DSCODONG_THAMDU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DSCODONG_THAMDU.Entity = null;
						previousValue.KIEMPHIEU_BAUCUs.Remove(this);
					}
					this._DSCODONG_THAMDU.Entity = value;
					if ((value != null))
					{
						value.KIEMPHIEU_BAUCUs.Add(this);
						this._MACD = value.MACD;
					}
					else
					{
						this._MACD = default(string);
					}
					this.SendPropertyChanged("DSCODONG_THAMDU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UNGVIEN_KIEMPHIEU_BAUCU", Storage="_UNGVIEN", ThisKey="ID_UngCu", OtherKey="ID", IsForeignKey=true)]
		public UNGVIEN UNGVIEN
		{
			get
			{
				return this._UNGVIEN.Entity;
			}
			set
			{
				UNGVIEN previousValue = this._UNGVIEN.Entity;
				if (((previousValue != value) 
							|| (this._UNGVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UNGVIEN.Entity = null;
						previousValue.KIEMPHIEU_BAUCUs.Remove(this);
					}
					this._UNGVIEN.Entity = value;
					if ((value != null))
					{
						value.KIEMPHIEU_BAUCUs.Add(this);
						this._ID_UngCu = value.ID;
					}
					else
					{
						this._ID_UngCu = default(Nullable<int>);
					}
					this.SendPropertyChanged("UNGVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KIEMPHIEU_BIEUQUYET")]
	public partial class KIEMPHIEU_BIEUQUYET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _LANBQ;
		
		private System.DateTime _NGAYBQ;
		
		private System.Nullable<bool> _LOAIBQ;
		
		private int _STTCD;
		
		private string _MACD;
		
		private System.Nullable<int> _TONGCD;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLANBQChanging(int value);
    partial void OnLANBQChanged();
    partial void OnNGAYBQChanging(System.DateTime value);
    partial void OnNGAYBQChanged();
    partial void OnLOAIBQChanging(System.Nullable<bool> value);
    partial void OnLOAIBQChanged();
    partial void OnSTTCDChanging(int value);
    partial void OnSTTCDChanged();
    partial void OnMACDChanging(string value);
    partial void OnMACDChanged();
    partial void OnTONGCDChanging(System.Nullable<int> value);
    partial void OnTONGCDChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    #endregion
		
		public KIEMPHIEU_BIEUQUYET()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANBQ", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LANBQ
		{
			get
			{
				return this._LANBQ;
			}
			set
			{
				if ((this._LANBQ != value))
				{
					this.OnLANBQChanging(value);
					this.SendPropertyChanging();
					this._LANBQ = value;
					this.SendPropertyChanged("LANBQ");
					this.OnLANBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBQ", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NGAYBQ
		{
			get
			{
				return this._NGAYBQ;
			}
			set
			{
				if ((this._NGAYBQ != value))
				{
					this.OnNGAYBQChanging(value);
					this.SendPropertyChanging();
					this._NGAYBQ = value;
					this.SendPropertyChanged("NGAYBQ");
					this.OnNGAYBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIBQ", DbType="Bit")]
		public System.Nullable<bool> LOAIBQ
		{
			get
			{
				return this._LOAIBQ;
			}
			set
			{
				if ((this._LOAIBQ != value))
				{
					this.OnLOAIBQChanging(value);
					this.SendPropertyChanging();
					this._LOAIBQ = value;
					this.SendPropertyChanged("LOAIBQ");
					this.OnLOAIBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTCD", DbType="Int NOT NULL")]
		public int STTCD
		{
			get
			{
				return this._STTCD;
			}
			set
			{
				if ((this._STTCD != value))
				{
					this.OnSTTCDChanging(value);
					this.SendPropertyChanging();
					this._STTCD = value;
					this.SendPropertyChanged("STTCD");
					this.OnSTTCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACD
		{
			get
			{
				return this._MACD;
			}
			set
			{
				if ((this._MACD != value))
				{
					this.OnMACDChanging(value);
					this.SendPropertyChanging();
					this._MACD = value;
					this.SendPropertyChanged("MACD");
					this.OnMACDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGCD", DbType="Int")]
		public System.Nullable<int> TONGCD
		{
			get
			{
				return this._TONGCD;
			}
			set
			{
				if ((this._TONGCD != value))
				{
					this.OnTONGCDChanging(value);
					this.SendPropertyChanging();
					this._TONGCD = value;
					this.SendPropertyChanged("TONGCD");
					this.OnTONGCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="VarChar(20)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYS_USERS")]
	public partial class SYS_USER
	{
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		public SYS_USER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UNGVIEN")]
	public partial class UNGVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private System.Nullable<int> _LoaiBC;
		
		private EntitySet<KIEMPHIEU_BAUCU> _KIEMPHIEU_BAUCUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnLoaiBCChanging(System.Nullable<int> value);
    partial void OnLoaiBCChanged();
    #endregion
		
		public UNGVIEN()
		{
			this._KIEMPHIEU_BAUCUs = new EntitySet<KIEMPHIEU_BAUCU>(new Action<KIEMPHIEU_BAUCU>(this.attach_KIEMPHIEU_BAUCUs), new Action<KIEMPHIEU_BAUCU>(this.detach_KIEMPHIEU_BAUCUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBC", DbType="Int")]
		public System.Nullable<int> LoaiBC
		{
			get
			{
				return this._LoaiBC;
			}
			set
			{
				if ((this._LoaiBC != value))
				{
					this.OnLoaiBCChanging(value);
					this.SendPropertyChanging();
					this._LoaiBC = value;
					this.SendPropertyChanged("LoaiBC");
					this.OnLoaiBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UNGVIEN_KIEMPHIEU_BAUCU", Storage="_KIEMPHIEU_BAUCUs", ThisKey="ID", OtherKey="ID_UngCu")]
		public EntitySet<KIEMPHIEU_BAUCU> KIEMPHIEU_BAUCUs
		{
			get
			{
				return this._KIEMPHIEU_BAUCUs;
			}
			set
			{
				this._KIEMPHIEU_BAUCUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KIEMPHIEU_BAUCUs(KIEMPHIEU_BAUCU entity)
		{
			this.SendPropertyChanging();
			entity.UNGVIEN = this;
		}
		
		private void detach_KIEMPHIEU_BAUCUs(KIEMPHIEU_BAUCU entity)
		{
			this.SendPropertyChanging();
			entity.UNGVIEN = null;
		}
	}
}
#pragma warning restore 1591
